### ISSUE TITLE
[Feature Request] Specify multirun sweeps in a config file

### ISSUE THREAD

**Issue by zaccharieramzi** [facebookresearch/hydra#1948] opened 2022-01-10 15:26 UTC
# 🚀 Feature Request

I would like to be able to specify multirun sweeps in a config file. 

## Motivation

**Is your feature request related to a problem? Please describe.**
I would like to be able to define my grid search in config files in order to have a way to save orderly rather than having to go through my search history for the last grid searches.

## Pitch

**Describe the solution you'd like**
Currently, the way to specify a sweep is via the command line like `python my_app.py -m +test.var=1,2`. I would like to be able to pass the sweep as a config file, for example ``python my_app.py -m +test=grid_search` where `test/grid_search.yaml` is in the config search path.

The content of `test/grid_search.yaml` could be for example:
```yaml
var@sweep: 
  - 1
  - 2
```

The `@sweep` is not part of the grammar but it could be to differentiate config variables that are not sweepable but really just lists.

**Describe alternatives you've considered**
I could have all my grid searches in scripts that are versioned but it doesnt feel natural and promotes a lot of copy pasting that I would like to avoid.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

## Additional context
I opened [an SO question](https://stackoverflow.com/q/70619014/4332585) on this topic, but it didnt get a lot of attention and I figured that it might be because there is simply no solution currently.

**Comment by pixelb** [comment] 2022-01-10 18:01
Yes this is something that is on our radar to implement hopefully for next release

**Comment by zaccharieramzi** [comment] 2022-01-10 18:03
Cool!
I'd be happy to help should you need it

**Comment by pixelb** [comment] 2022-01-10 18:12
Does commit 20bd227ad cover your use case?
That was implemented as part of issue #1376

**Comment by zaccharieramzi** [comment] 2022-01-10 18:17
I think it does mostly so cool! Sorry I hadn't seen #1376 

I have one additional feature request linked to this: do you think it would be possible to make it work with [this type of sweep](https://github.com/facebookresearch/hydra/issues/1258#issuecomment-754341537)? i.e. `python my_app.py -m '+top={a:10,b:20},{a:100,b:200}'`

If you want I can repost that request on #1376

**Comment by pixelb** [comment] 2022-01-11 00:42
closing as a duplicate of #1376 for now.
Feel free to further discuss there. thanks

**Closed by pixelb** 2022-01-11 00:42 UTC
Labels: duplicate, enhancement
