### ISSUE TITLE
PicklingError using torch_xla with the RQ Launcher

### ISSUE THREAD

**Issue by viyx** [facebookresearch/hydra#1252] opened 2021-01-01 17:32 UTC
# 🐛 Bug
## Description
I can't use hydra rq_launcher to execute jobs with multiprocessing.
May I should use another sequence of calls in my code or is it expected behavior of hydra?

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

I use torch_xla lib.

My code is:

```
import torch_xla

def map_fn(rank):
    print(rank)
    return rank


@hydra.main(config_path='conf', config_name="config")
def main(cfg: DictConfig):
    torch_xla.distributed.xla_multiprocessing.spawn(map_fn, nprocs=8, start_method='spawn')


if __name__ == '__main__':
    OmegaConf.register_resolver("wandb_id", lambda: generate_id())
    main()
```

the code of  torch_xla.distributed.xla_multiprocessing.spawn for quick overview

 ```
 if not _is_xla_config():
    # If this is not an XLA setup, jump to normal multi-processing.
    return _run_direct(fn, args, nprocs, join, daemon, start_method)

  pf_cfg = _pre_fork_setup(nprocs)
  if pf_cfg.num_devices == 1:
    _start_fn(0, pf_cfg, fn, args)
  else:
    return torch.multiprocessing.start_processes(
        _mp_start_fn,
        args=(pf_cfg, fn, args),
        nprocs=pf_cfg.num_devices,
        join=join,
        daemon=daemon,
        start_method=start_method)
```

I get this error on worker:
```
17:04:13 Worker rq:worker:657678dfb2d14e1aa46495aea0e0b494: started, version 1.7.0
17:04:13 Subscribing to channel rq:pubsub:657678dfb2d14e1aa46495aea0e0b494
17:04:13 *** Listening on default...
17:04:13 Cleaning registries for queue: default
17:04:13 default: n_epochs=5 train=tpu n_cores=8 (07b1aee1-f5b0-4ae6-92f7-568fd58c03d3)
WARNING:root:TPU has started up successfully with version pytorch-1.7
17:04:15 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 975, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 696, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/rq/job.py", line 719, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hydra_plugins/hydra_rq_launcher/_core.py", line 43, in execute_job
    job_subdir_key="hydra.sweep.subdir",
  File "/usr/local/lib/python3.6/dist-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "test_hydra.py", line 316, in main
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 148, in start_processes
    process.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function map_fn at 0x7f8a9a0f3ea0>: attribute lookup map_fn on __main__ failed

17:04:15 Worker rq:worker:657678dfb2d14e1aa46495aea0e0b494: finished executing 1 jobs, quitting
17:04:15 Unsubscribing from channel rq:pubsub:657678dfb2d14e1aa46495aea0e0b494
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 2 leaked semaphores to clean up at shutdown
  len(cache))
```

## Expected Behavior
The code works with **nprocs=1**. I expect it it should works with **nprocs=8**.
I really don't understand if hydra is supporting tasks with multiprocessing and how to use it in such a case.

## System information
- **Hydra Version** :  1.0.4
- **hydra-rq-launcher**: 1.0.1
- **Python version** : 3.6 
- **Virtual environment type and version** : 
- **Operating system** :  Linux

**Comment by omry** [comment] 2021-01-01 17:48
I have seen similar reports on torch.distributed [here](#1180).
Please follow the discussion there to try to narrow things down.

A few things to try:
1. Try other launchers.
2. Create a minimal repro without Hydra (using the underlying launcher code)
3. Create a minimal repro without the launcher code (similar to last repro in #1180).

**Comment by viyx** [comment] 2021-01-01 19:31
I simplify my code a bit and try other launchers.

test_hydra.py:
```
from torch_xla.distributed.xla_multiprocessing import spawn
import hydra

def map_fn(rank):
    print(rank)
    return rank


@hydra.main(config_name="config_test_hydra")
def main(cfg):
    spawn(map_fn, nprocs=cfg.n_cores, start_method='spawn')


if __name__ == '__main__':
    main()
```
**basic launcher**:

```
(pytorch) root@3c76d0dd342e:/workspaces/arc-nn# python test_hydra.py -m hydra/launcher=basic n_cores=8,1
[2021-01-01 19:14:17,918][HYDRA] Launching 2 jobs locally
[2021-01-01 19:14:17,919][HYDRA]        #0 : n_cores=8
2
3
0
5
4
1
7
6
[2021-01-01 19:14:29,131][HYDRA]        #1 : n_cores=1
0
```
**joblib_launcher**:
```
(pytorch) root@3c76d0dd342e:/workspaces/arc-nn# python test_hydra.py -m hydra/launcher=joblib n_cores=8,1
[2021-01-01 19:15:43,610][HYDRA] Joblib.Parallel(n_jobs=-1,backend=loky,prefer=processes,require=None,verbose=0,timeout=None,pre_dispatch=2*n_jobs,batch_size=auto,temp_folder=None,max_nbytes=None,mmap_mode=r) is launching 2 jobs
[2021-01-01 19:15:43,610][HYDRA] Launching jobs, sweep output dir : multirun/2021-01-01/19-15-42
[2021-01-01 19:15:43,611][HYDRA]        #0 : n_cores=8
[2021-01-01 19:15:43,612][HYDRA]        #1 : n_cores=1
0
joblib.externals.loky.process_executor._RemoteTraceback: 

"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra_plugins/hydra_joblib_launcher/_core.py", line 47, in execute_job
    job_subdir_key="hydra.sweep.subdir",
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "test_hydra.py", line 317, in main
    spawn(map_fn, nprocs=cfg.n_cores, start_method='spawn')
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 382, in spawn
    return _run_direct(fn, args, nprocs, join, daemon, start_method)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 346, in _run_direct
    fn, args=args, nprocs=nprocs, join=join, daemon=daemon)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 247, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 196, in start_processes
    process.start()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function map_fn at 0x7f9ae1aeb268>: attribute lookup map_fn on __main__ failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/_internal/utils.py", line 358, in <lambda>
    overrides=args.overrides,
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra_plugins/hydra_joblib_launcher/joblib_launcher.py", line 46, in launch
    launcher=self, job_overrides=job_overrides, initial_job_idx=initial_job_idx
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra_plugins/hydra_joblib_launcher/_core.py", line 110, in launch
    for idx, overrides in enumerate(job_overrides)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
_pickle.PicklingError: Can't pickle <function map_fn at 0x7f9ae1aeb268>: attribute lookup map_fn on __main__ failed
```

**Comment by omry** [comment] 2021-01-01 19:55
Okay, so this problem is common to multiple launchers. the common denominator is probably cloudpickle.
Can you try to take Hydra out of the equation by working directly with joblib in a simpler repro?

the next step would be to take joblib out of the equation (similar to my comment [here](https://github.com/facebookresearch/hydra/issues/1180#issuecomment-739148176)).

**Comment by viyx** [comment] 2021-01-02 00:30
I can provide more examples later, mainly I think the problem not in cloudpickle at all.

It seems the issue is connected with multiprocessing+pickle+decorator setting. We see that pickle can't lookup function in main, it is possible due to decoration and wrapping in hydra.main I think.

I put out function to another file make import in main and it works fine. Pickle find out my function. Also there is some intuition [here](https://stackoverflow.com/questions/9336646/python-decorator-with-multiprocessing-fails).

The last working code:

```
from torch_xla.distributed.xla_multiprocessing import spawn
import hydra
from map_fn import map_fn


@hydra.main(config_name="config_test_hydra")
def main(cfg):
    from map_fn import map_fn
    spawn(map_fn, nprocs=cfg.n_cores, start_method='spawn')


if __name__ == '__main__':
    main()
```

**Comment by omry** [comment] 2021-01-02 00:33
cloudpickle should be able handles this properly. I guess pytorch does not depend on it?

**Comment by viyx** [comment] 2021-01-02 12:31
I'll try to debug later to clarify things.

**Comment by omry** [comment] 2021-01-02 22:24
I tried to repro and realized I don't know how to get torch_xla.
Is there a package I can install? I would rather not need to reproduce this over Google's hardware.

**Comment by viyx** [comment] 2021-01-03 08:22
For local development I use the docker:
`gcr.io/tpu-pytorch/xla:nightly_3.6`

Also you need to add these flags for cpu xla support(no tpu):
```
os.environ['XRT_DEVICE_MAP'] = 'CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0'
os.environ['XRT_WORKERS'] = 'localservice:0;grpc://localhost:40934'
```
I've signed up in chat as viy

**Comment by viyx** [comment] 2021-01-27 21:45
I found warning about non-declaring functions in main module in [RQ docs](https://python-rq.org/docs/).

> Make sure that the function’s `__module__` is importable by the worker. In particular, this means that you cannot enqueue functions that are declared in the `__main__` module.

So, workaround is keeping decorated main in separate file. Like [here](https://github.com/facebookresearch/hydra/issues/1252#issuecomment-753409429)

**Comment by omry** [comment] 2021-01-27 21:51
Okay, so looks like this is a limitation of rq.
cloudpickle in general is able to serialize functions declared in the main file but I am guessing rq is not using it.

Closing as this is not a bug in Hydra ,feel free to continue discussing here.

**Comment by viyx** [comment] 2021-01-27 21:55
it's strange because the same issue I saw in joblib_launcher, [link](https://github.com/facebookresearch/hydra/issues/1252#issuecomment-753371784)

**Comment by omry** [comment] 2021-01-27 22:01
Gotcha.

In any case, this issue is not something I am likely to spend time looking into in the near future so I am happy to see you have found a workaround.
If you discover the root cause please update here.

**Comment by viyx** [comment] 2021-01-27 22:08
OK, thank you anyway

**Comment by omry** [comment] 2021-06-04 01:04
Since this issue, I have seen multiple other reports where cloudpickle is not behaving well when pickling things defined int he main module.
Based on your workaround, this seems like one of these cases.

As xla is out of scope anyway (and is rather difficult to test because of the environment requirements) I am closing this.
Feel free to followup.

**Closed by omry** 2021-06-04 01:04 UTC
Labels: bug, help wanted
