### ISSUE TITLE
[Bug] Setting sweep dir to cwd causes interpolation error

### ISSUE THREAD

**Issue by ashleve** [facebookresearch/hydra#2247] opened 2022-05-29 23:51 UTC
# 🐛 Bug

I found an edge case when setting sweep dir results in interpolation error.

Config:
```yaml
hydra:
  sweep:
    dir: ${hydra:runtime.cwd}/logs/
```

Running `python main.py -m` results in the following stack trace:
```
Traceback (most recent call last):
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 163, in sweep
    sweep_dir = Path(self.config.hydra.sweep.dir)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 361, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    return self._get_impl(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 453, in _get_impl
    return self._resolve_with_default(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 98, in _resolve_with_default
    resolved_node = self._maybe_resolve_interpolation(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 719, in _maybe_resolve_interpolation
    return self._resolve_interpolation_from_parse_tree(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 769, in resolve_parse_tree
    raise InterpolationResolutionError(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/base.py", line 694, in _evaluate_custom_resolver
    return resolver(
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 439, in resolver_wrapper
    ret = resolver(*args, **kwargs)
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/hydra/core/utils.py", line 220, in <lambda>
    lambda path: OmegaConf.select(cast(DictConfig, HydraConfig.get()), path),
  File "/home/ukasz/miniconda3/envs/myenv/lib/python3.8/site-packages/hydra/core/hydra_config.py", line 31, in get
    raise ValueError("HydraConfig was not set")
omegaconf.errors.InterpolationResolutionError: ValueError raised while resolving interpolation: HydraConfig was not set
    full_key: hydra.sweep.dir
    reference_type=SweepDir
    object_type=SweepDir
```

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## Expected Behavior
I know I could just omit the `${hydra:runtime.cwd}` since hydra would create output directory in cwd either way by default, but:
1. It doesn't throw error if I set `hydra.run.dir=${hydra:runtime.cwd}/logs` so I see no reason for it not working with sweep dir
2. I wanted to do something like this in my project simply because it seems clean:
```yaml
# assume current working directory is the root dir
root_dir: ${hydra:runtime.cwd}
data_dir: ${root_dir}/data
log_dir: ${root_dir}/logs

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}
  sweep:
    dir: ${log_dir}/multiruns/${now:%Y-%m-%d}
```

## System information
- **Hydra Version** :  1.2
- **Python version** : 3.10
- **Virtual environment type and version** : conda 
- **Operating system** : linux

**Comment by ashleve** [comment] 2022-05-30 00:05
Sorry, did not realize there were already similar issues: https://github.com/facebookresearch/hydra/issues/1301 https://github.com/facebookresearch/hydra/issues/1786

Am I correct to assume this is desired behavior for now?

**Comment by Jasha10** [comment] 2022-05-31 15:13
Hi @ashleve,

> Am I correct to assume this is desired behavior for now?

Yes.

I believe the problem is that the `${hydra:...}` resolver relies on some state being set (i.e. `HydraConfig`). The HydraConfig state is set once for each job in the sweep. Meanwhile, the sweeper itself (e.g. BasicSweeper) gets invoked *before* the HydraConfig is set. The sweeper has to access the `hydra.sweep.dir` config, which leads to an error if the `${hydra:..}` resolver is involved.

**Comment by jieru-hu** [comment] 2022-06-10 21:28
thanks for the issue @ashleve  - this is expected and we do not have any plan to change it for now (see my comment in https://github.com/facebookresearch/hydra/issues/1786)

closing...

**Closed by jieru-hu** 2022-06-10 21:28 UTC
Labels: bug
