### ISSUE TITLE
Dynamic schema with many different defaults

### ISSUE THREAD

**Issue by EricMichaelSmith** [facebookresearch/hydra#1023] opened 2020-09-29 12:48 UTC
# 🚀 Feature Request

The docs [here](https://www.internalfb.com/intern/staticdocs/hydra/docs/tutorials/structured_config/dynamic_schema) detail defining a dynamic schema in which different config files can be chosen; it'd also be nice to have the ability to set the `defaults` list based on which schema we're choosing. For instance, in the example in the docs, `MySQLConfig` and `PostGreSQLConfig` would each have their own `defaults`.

## Motivation

I have two config files representing different schema, and two sets of defaults, one for each of those schema. I'd like to be able to specify which set of defaults and which config file to use on the command line, ideally with one single command-line flag.

## Pitch

**Describe the solution you'd like**
Perhaps an easy way to set defaults per schema? For instance, this could be a new argument in the signature of `ConfigStore.store()`

**Describe alternatives you've considered**
Honestly, I'll probably fall back to just having two different run scripts for now, each one tied to each of my config files and sets of defaults. I'd like to scale this up eventually to many config files and many sets of defaults, and I'll have to reassess then whether there is a better structure that I can use for this.

**Comment by omry** [comment] 2020-09-29 16:20
Hi @EricMichaelSmith, thanks for the feature request.
I believe this is a duplicate of #171, which is planned for Hydra 1.1.

**Closed by omry** 2020-09-29 16:20 UTC
Labels: enhancement
