### ISSUE TITLE
[Bug] OmegaConf.save doesn't seem to be interpolated a value

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/hydra#1038] opened 2020-10-06 17:16 UTC
# 🐛 Bug
## Description

I was using Pytorch Lightning and OmegaConf with hydra generated configuration. And Omegaconf fails to save the hparams from`LightningModule` with OmegaConf

The exact line is there: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/saving.py#L372

I am not sure why yet. I can access correctly num_classes in debugger, but OmegaConf.save raise a ConfigKeyError

```
(Pdb) hparams["criterion"].params.num_classes
90
(Pdb) hparams
{'name': 'efficientdet-d0', 'compound_coef': 0, 'backbone': 'efficientnet-b0', 'img_size': [512, 64], 'r_input': 512, 'w_bifpn': 64, 'd_bifpn': 3, 'd_class': 3, 'min_level': 3, 'max_level': 7, 'num_levels': '7 - 3 + 1', 'params': '3.9M', 'num_examples_per_epoch': 117266, 'criterion': {'_target_': 'src.cv_obj_det.utils.tools.DetectionLoss', 'params': {'alpha': 0.25, 'gamma': 1.5, 'delta': 0.1, 'box_loss_weight': 50, 'num_classes': '${dataset.params.num_classes}'}}, 'optimizer': {'_target_': 'torch.optim.SGD', 'params': {'lr': 0.04, 'weight_decay': 4e-05, 'momentum': 0.9}}, 'aspect_ratios': [[1.0, 1.0], [1.4, 0.7], [0.7, 1.4]], 'num_scales': 3, 'anchor_scale': 4.0, 'num_anchors': 9, 'num_classes': 90}
(Pdb) OmegaConf.save(hparams, config_yaml, resolve=True)
*** omegaconf.errors.ConfigKeyError: str interpolation key 'dataset.params.num_classes' not found
(Pdb) OmegaConf.save(OmegaConf.create(hparams), config_yaml, resolve=True)
*** omegaconf.errors.ConfigKeyError: str interpolation key 'dataset.params.num_classes' not found
```

```
# Model is instantiated this way
model = hydra.utils.instantiate(cfg.model, **data_module.hyper_parameters)

class EfficientDetModel(pl.LightningModule):
    def __init__(self, *args, **kwargs):
        super().__init__()

       # hparams are created there as list of all kwargs and args
        self.save_hyperparameters()
```

I am investigating but any guidance would be appreciated :)

Works fine if I do

```
class EfficientDetModel(pl.LightningModule):
    def __init__(self, *args, **kwargs):
        super().__init__()

        kwargs["criterion"].params.num_classes = kwargs["criterion"].params.num_classes

        self.save_hyperparameters()
```

## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro

## To reproduce

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information
- **Hydra Version** :  
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by omry** [comment] 2020-10-06 17:35
Taking a look at your error, I suspect it's because the OmegaConf config is placed in a dictionary parent instead of an OmegaConf DictConfig parent.
this is not a supported use case for OmegaConf and the fact it's not working is not a bug.

Also, this has nothing to do with save() (you can call `OmegaConf.to_container(cfg, resolve=True)` directly and see what it does.

PyTorch Lightning is doing all sorts of weird things when it saves OmegaConf configs and if you have a problem there you should file an issue on that project (again, with a minimal example).

Finally, a minimal repro will make all the difference in the world in people's ability to look at the actual problem and make suggestions (and that's true if you file this against OmegaConf, Hydra or PL).

I am closing this because from the little information you provided it seems like it's not a bug in OmegaConf (and certainly not a bug in Hydra), but probably a misuse in PL.
Feel free to continue discussing here and if that turns out to be a wrong assessment we can reopen.

**Closed by omry** 2020-10-06 17:35 UTC
Labels: bug

**Comment by omry** [comment] 2020-10-06 17:38
Also, as a rule of thumb:
A minimal repo should not include any external dependencies.
- If you think it's a bug in OmegaConf, the repro should rely on OmegaConf and any of it's own dependencies.
- If you think it's a bug in Hydra the repro should rely on Hydra and it's own dependencies).
If you need PyTorch Lightning to reproduce the problem this should first be evaluated against PyTorch Lightning to be sure this is not a bug there. if the decision is that it is a bug in Hydra or OmegaConf you should be able to reproduce it without PL when you submit a bug report against Hydra or OmegaConf.

**Comment by tchaton** [comment] 2020-10-06 17:43
Dear @omry,

You are entirely right ! It is a misuse from PL. I will try open a PR on PL with a fix. Thanks a lot for taking time to answer :)

Best regards,
T.C

**Comment by omry** [comment] 2020-10-06 17:46
It may prove tricky because PL is trying to not depend on OmegaConf.
