### ISSUE TITLE
[Bug] String argumant incorrectly parsed as integer

### ISSUE THREAD

**Issue by weiwei-ww** [facebookresearch/hydra#1163] opened 2020-11-19 11:06 UTC
# 🐛 Bug
## Description

A string argument is incorrectly parsed as an integer if this string only contains numbers and underscores.

## To reproduce

In _config/hydra_test.yaml_:
```
id: ???
```
In _hydra_test.py_:
```
import hydra

@hydra.main(config_path='config', config_name='hydra_test')
def main(cfg):
    print(cfg.id)

if __name__ == '__main__':
    main()
```
Run the following command:
```
python hydra_test.py id=1_1_1
```
or:
```
python hydra_test.py id="1_1_1"
```

## Expected Behavior

The expected output is:
```
1_1_1
```
However, the program outputs this instead:
```
111
```

## System information
- **Hydra Version** :  1.0.3
- **Python version** : 3.7.9
- **Operating system** : Ubuntu 20.04

**Comment by omry** [comment] 2020-11-19 11:40
Hydra is parsing integers similar to Python:
```
>>> 1_1_1
111
>>> '1_1_1'
'1_1_1'
```

The problem with
```
$ python hydra_test.py id="1_1_1"
```
Is that your shell is interpreting the quotes instead of Hydra.
You need to quote twice, try:
```
$ python hydra_test.py 'id="1_1_1"'
```

You can learn more about the command line parser [here](https://hydra.cc/docs/advanced/override_grammar/basic).

Closing as this is by design.

**Closed by omry** 2020-11-19 11:40 UTC
Labels: bug
