### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SZiesche** [facebookresearch/hydra#2588] opened 2023-02-15 10:42 UTC
# 🐛 Bug
## Description
When configs based on Baseclasses are nested more than once merging doesn't work anymore.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```python
from dataclasses import dataclass, field
from typing import Any, List

import hydra.utils
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING

# I have multiple datasets


@dataclass
class DataConfig:
    """This is just a common base class."""


@dataclass
class Dataset1Config(DataConfig):
    some_member1: int = 1


@dataclass
class Dataset2Config(DataConfig):
    some_member2: int = 2


# I register them at some place in my folder structure.
cs = ConfigStore.instance()
cs.store(group="some/data/folder", name=Dataset1Config.__name__, node=Dataset1Config)
cs.store(group="some/data/folder", name=Dataset2Config.__name__, node=Dataset2Config)


# I have multiple training routines (listed only one here deriving from a common base class)


@dataclass
class TrainingConfig:
    pass


@dataclass
class SpecialTrainingConfig:
    some_member4: int = 4


cs.store(group="some/training/folder", name=SpecialTrainingConfig.__name__, node=SpecialTrainingConfig)


# finally I have multiple models that can be trained differently. Model1 is usually trained by the special training, so
# I want to have this as a default.


@dataclass
class ModelConfig:
    """This is just a common base class."""


@dataclass
class Model1Config(ModelConfig):
    defaults: List[Any] = field(default_factory=lambda: [{"/some/training/folder@training": "SpecialTrainingConfig"}])

    training: TrainingConfig = MISSING


@dataclass
class Model2Config(ModelConfig):
    some_member: int = 3


# I register them at some place in my folder structure.
cs.store(group="some/model/folder", name=Model1Config.__name__, node=Model1Config)
cs.store(group="some/model/folder", name=Model2Config.__name__, node=Model2Config)


# main.py:
# for the main routine of my machine learning project, I also have a config.
# usually I would use dataset1, so I have this as a default. But the model changes often and I don't want to use a
# default there.
@dataclass
class ScriptConfig:
    defaults: List[Any] = field(default_factory=lambda: [{"some/data/folder@dataset": "Dataset1Config"}, "_self_"])

    dataset: DataConfig = MISSING
    model: ModelConfig = MISSING


cs.store(name="ScriptConfig", node=ScriptConfig)


@hydra.main(config_name="my_config2", version_base="1.2", config_path=".")
def main(cfg):
    print(cfg)


if __name__ == "__main__":
    main()
```

the `my_config2.yaml` looks like this: 
```yaml
defaults:
  - ScriptConfig
  - /some/model/folder@model: Model1Config
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 542, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 432, in _map_merge
    dest[key] = src._get_node(key)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 310, in __setitem__
    self._format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 545, in _set_item_impl
    self._validate_set(key, value)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 476, in _get_node
    self._validate_get(key)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigKeyError: Key 'training' not in 'ModelConfig'
    full_key: model.training
    reference_type=ModelConfig
    object_type=ModelConfig
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 263, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 544, in _compose_config_from_defaults_list
    raise ConfigCompositionException(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 542, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 432, in _map_merge
    dest[key] = src._get_node(key)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 310, in __setitem__
    self._format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
    self.__set_impl(key=key, value=value)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 545, in _set_item_impl
    self._validate_set(key, value)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 476, in _get_node
    self._validate_get(key)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/zis2rng/Coding/letas_workspaces/dev1-letas/.venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
hydra.errors.ConfigCompositionException: In 'some/training/folder/SpecialTrainingConfig': ConfigKeyError raised while composing config:
Key 'training' not in 'ModelConfig'
    full_key: model.training
    reference_type=ModelConfig
    object_type=ModelConfig
python-BaseException
```

## Expected Behavior
I would expect that this runs through smoothly as it does, when I nest only one level. E.g., by choosing the following `my_config2.yaml`:
```
defaults:
  - /some/model/folder@_global_: Model1Config
```

## System information
- **Hydra Version** :  1.3.1
- **Python version** :  3.8.10
- **Virtual environment type and version** :  poetry/venv
- **Operating system** : ubuntu

**Comment by SZiesche** [comment] 2023-02-27 06:47
I investigated this problem a bit more and saw, that the information, that `Model1Config` inherits from `ModelConfig` is "forgotten" in `hydra/_internal/config_loader_impl.py` in the function 

```python
    @staticmethod
    def _embed_result_config(
        ret: ConfigResult, package_override: Optional[str]
    ) -> ConfigResult:
        package = ret.header["package"]
        if package_override is not None:
            package = package_override

        if package is not None and package != "":
            cfg = OmegaConf.create()
            OmegaConf.update(cfg, package, ret.config, merge=False)
            ret = copy.copy(ret)
            ret.config = cfg

        return ret
```

**Comment by SZiesche** [comment] 2023-02-27 09:27
I'm actually not sure, if this behavior is intended (for some unknown reason), because there is no documentation in the code in any of these smaller utility functions. So I also have no clue what to test against.

If there is some more detailed documentation I missed so far, please let me know, then I could have a look.

**Comment by omry** [comment] 2023-02-27 15:00
I would need to find the time to reproduce locally to be sure, but from your description in your previous comment it is not intended.
Can you explain how you have come to the conclusion that the parent class of the DictConfig is not retained after the update call here?

```python
OmegaConf.update(cfg, package, ret.config, merge=False)
```

**Comment by SZiesche** [comment] 2023-02-28 17:05
I have debugged through the code and had a breakpoint at the beginning of the function and at the end of the function. I printed `ret` both times. This is the result:

```
ret.config._metadata
Out[2]: ContainerMetadata(ref_type=typing.Any, object_type=<class '__main__.Dataset1Config'>, optional=True, key=None, flags={'HYDRA_REMOVE_TOP_LEVEL_DEFAULTS': True}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {}), key_type=typing.Any, element_type=typing.Any)
ret.config._metadata
Out[3]: ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True, key=None, flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {}), key_type=typing.Any, element_type=typing.Any)
```

You can see that the `object_type` changed from `Dataset1Config` to `dict`. So, afterwards he can't check anymore whether the config originated from a dataclass that inherited from `DatasetConfig`. Same holds true for `ModelConfig` later on. 

However I still wonder, why this only becomes a problem, when the nesting is 2 instead of 1.

**Comment by omry** [comment] 2023-03-01 15:29
@Jasha10, can you take a look? this looks like an edge case with the current embedding of a config in a package.

**Comment by SZiesche** [comment] 2023-04-14 07:21
ping

**Comment by odelalleau** [comment] 2023-04-14 15:45
> ping

It looks like you may have figured out the source of the bug, if that's the case you may want to try fixing it and submitting a PR. If no existing test is broken it should be fine.

**Comment by SZiesche** [comment] 2023-04-14 17:16
> I'm actually not sure, if this behavior is intended (for some unknown reason), because there is no documentation in the code in any of these smaller utility functions. So I also have no clue what to test against.
> 
> If there is some more detailed documentation I missed so far, please let me know, then I could have a look.

sorry, I can only repeat myself. Without any proper documentation, I can't do anything. If you've got some docs hidden somewhere I'm more than happy to dig into the issue myself. But until then it would be cool if you checkout my toy example.

**Comment by odelalleau** [comment] 2023-04-14 17:23
> > I'm actually not sure, if this behavior is intended (for some unknown reason), because there is no documentation in the code in any of these smaller utility functions. So I also have no clue what to test against.
> > If there is some more detailed documentation I missed so far, please let me know, then I could have a look.
> 
> sorry, I can only repeat myself. Without any proper documentation, I can't do anything. If you've got some docs hidden somewhere I'm more than happy to dig into the issue myself. But until then it would be cool if you checkout my toy example.

Although it's always possible that something may not be properly tested, overall the test suite is pretty extensive, so if you break something it should come up in tests. I'm sorry I don't have time to check out your toy example right now -- maybe in a few weeks.

**Comment by SZiesche** [comment] 2023-04-17 08:07
A side question, how do you manage the whole project without docstrings (at least in `hydra/_internal/config_loader_impl.py`)?

**Comment by Jasha10** [comment] 2023-04-18 12:26
@SZiesche I'm not convinced that this is a bug. I've been able to get your toy example working by making two changes:
- Make `training` a field of the base class `ModelConfig` rather than a field of the derived class `Model1Config`.
- Make `SpecialTrainingConfig` into a subclass of `TrainingConfig`.

Here's the diff:
```diff
$ diff -u original.py modified.py
--- original.py 2023-04-18 07:24:04.102760859 -0500
+++ modified.py 2023-04-18 07:24:43.863026153 -0500
@@ -38,7 +38,7 @@


 @dataclass
-class SpecialTrainingConfig:
+class SpecialTrainingConfig(TrainingConfig):
     some_member4: int = 4


@@ -53,13 +53,13 @@
 class ModelConfig:
     """This is just a common base class."""

+    training: TrainingConfig = MISSING
+

 @dataclass
 class Model1Config(ModelConfig):
     defaults: List[Any] = field(default_factory=lambda: [{"/some/training/folder@training": "SpecialTrainingConfig"}])

-    training: TrainingConfig = MISSING
-

 @dataclass
 class Model2Config(ModelConfig):
```

Here's the output:
```python
$ python modified.py
{'dataset': {'some_member1': 1}, 'model': {'training': {'some_member4': 4}}}
```

**Comment by SZiesche** [comment] 2023-04-18 14:08
First of all, thank you for having a first look! 
While the first change (adding `TrainingConfig` as a base class) was certainly missed by me, the second change is actually unwanted. `Model1Config` will most likely have members that are not part of `ModelConfig`. That this member is `training` in the current example and that this in principle might make sense for all models is a mere coincidence here. So your solution doesn't work in the end.

However, I also took some time to step through the hydra code and obtain some understanding of whats going on. One thing I observed was, that at some point `training` is a `DictConfig` without any items in it (because it is initialized with `MISSING`) and it seems that this is connected to the fact that it forgets that it is actually a `TrainingConfig`. (at this point you can't look into `training._metadata` at all).
Maybe these new bits of information help to resolve this mystery. Currently I'm tending to think, this is rather an `OmegaConf` problem than a hydra problem.

**Comment by Jasha10** [comment] 2023-04-18 16:01
> the second change is actually unwanted.

I see. In that case, try putting `_self_` at the *beginning* of `Model1Config` defaults list. (When you omit `_self_`, the default behavor for Hydra 1.2 is equivalent to adding `_self_` at the *end* of the defaults list.)

```diff
$ diff -u original.py modified.py
--- original.py 2023-04-18 10:56:53.408898323 -0500
+++ modified.py 2023-04-18 10:56:22.308733510 -0500
@@ -38,7 +38,7 @@


 @dataclass
-class SpecialTrainingConfig:
+class SpecialTrainingConfig(TrainingConfig):
     some_member4: int = 4


@@ -62,7 +62,8 @@
 class Model1Config(ModelConfig):
     defaults: List[Any] = field(
         default_factory=lambda: [
-            {"/some/training/folder@training": "SpecialTrainingConfig"}
+            "_self_",
+            {"/some/training/folder@training": "SpecialTrainingConfig"},
         ]
     )
```
```python
 $ python modified.py
{'dataset': {'some_member1': 1}, 'model': {'training': {'some_member4': 4}}}
```

I'll follow this comment with a note on why this works.

**Comment by Jasha10** [comment] 2023-04-18 16:10
I created the following pure-omegaconf repro for the error message from your toy example:
```python
# omc_repro.py
from dataclasses import dataclass
from omegaconf import MISSING, OmegaConf

@dataclass
class DataConfig: pass

@dataclass
class Dataset1Config(DataConfig):
    some_member1: int = 1

@dataclass
class TrainingConfig: pass

@dataclass
class SpecialTrainingConfig(TrainingConfig):
    some_member4: int = 4

@dataclass
class ModelConfig: pass

@dataclass
class Model1ConfigNoDefaults(ModelConfig):
    training: TrainingConfig = MISSING

@dataclass
class ScriptConfigNoDefaults:
    dataset: DataConfig = MISSING
    model: ModelConfig = MISSING

if __name__ == "__main__":
    defaults = [
        {"dataset": Dataset1Config()},
        ScriptConfigNoDefaults(),
        {"model": {"training": SpecialTrainingConfig()}},
        {"model": Model1ConfigNoDefaults()},
    ]
    cfg = OmegaConf.merge(*defaults)
    print(cfg)
```
```python
$ python omc_repro.py
Traceback (most recent call last):
...
omegaconf.errors.ConfigKeyError: Key 'training' not in 'ModelConfig'
    full_key: model.training
    reference_type=ModelConfig
    object_type=ModelConfig
```
The above call to `OmegaConf.merge` is roughly equivalent to what Hydra does when composing the final config from the defaults list. The error is resolved by swapping the last two items in the list:
```diff
$ diff -u omc_repro.py omc_fixed.py
--- omc_repro.py        2023-04-18 11:01:14.878608463 -0500
+++ omc_fixed.py        2023-04-18 11:05:12.352116278 -0500
@@ -31,8 +31,8 @@
     defaults = [
         {"dataset": Dataset1Config()},
         ScriptConfigNoDefaults(),
-        {"model": {"training": SpecialTrainingConfig()}},
         {"model": Model1ConfigNoDefaults()},
+        {"model": {"training": SpecialTrainingConfig()}},
     ]
     cfg = OmegaConf.merge(*defaults)
     print(cfg)
```
```python
$ python omc_fixed.py
{'dataset': {'some_member1': 1}, 'model': {'training': {'some_member4': 4}}}
```
Swapping those items in the defaults list corresponds to putting `_self_` first in the `Model1Config` defaults.

The problem with the original order is that `OmegaConf.merge` works in an order-dependent manner; once the first two items in the defaults list are merged, there is no `model.training` key in the config, so setting `model.training=SpecialTrainingConfig` does not work. Setting `model=Model1Config` first resolves this; as merging `Model1Config` introduces a `model.training` key to the config, enabling `SpecialTrainingConfig` to be merged successfully.

**Comment by SZiesche** [comment] 2023-04-19 12:43
thank you a lot for this enlightening explanation of the whole issue! Good to know that this is in the end `OmegaConf` related.

Though I have to say, that I find this behavior a bit unexpected, as I would expect from the code
```
@dataclass
class ScriptConfigNoDefaults:
    dataset: DataConfig = MISSING
    model: ModelConfig = MISSING
```
that I can always pass a `ModelConfig` to `model`.

**Comment by Jasha10** [comment] 2023-04-19 16:10
> I would expect ... that I can always pass a `ModelConfig` to `model`.

The error isn't caused by passing a `ModelConfig` to `model`; it's caused by passing a `SpecialTrainingConfig` to `model.training` (which `Model1Config` does support but the base class `ModelConfig` does not support).

**Closed** 2023-04-19 16:10 UTC
Labels: bug

**Comment by omry** [comment] 2023-04-20 03:09
This may be inaccurate as I did not debug this, but:
1. There is no assignment here, only merging.
2. While the object is MISSING, you can merge any legal subclass into it. If due to merge order error you end up merging a subclass and then a superclass onto the same node, then we may have the problem.

**Comment by SZiesche** [comment] 2023-04-20 16:42
ok, after having studied your example once more, I understood the "pure OmegaConf example". 
But I had not understood the hydra thing. So I once more took a look at the hydra code. With an even better idea, where to look, I realized, that all the values in the defaults list are turned into a tree with ordered children in the obvious way (see `_create_defaults_tree()`). Then the tree is turned into a list via a _**depth-first-walk**_ (see `_tree_to_list()`). At that point, the defaults list more or less looks like the list in the "pure OmegaConf example" and the behavior is clear.

So my confusion originated from the fact, that I always assumed there would be a **breadth-first-walk** to really finish one config first before using it somewhere else.

Thank you again for having made this clear.

**Comment by omry** [comment] 2023-04-21 12:09
There are two passes because a config can override the defaults list choices of a previously included config.
This is somehow described in [The Defaults List](https://hydra.cc/docs/advanced/defaults_list/#overriding-config-group-options).

**Comment by zqkdlmu2023** [comment] 2024-09-11 13:06
I have also encountered the same problem. How did you solve it.

**Comment by SZiesche** [comment] 2024-09-11 15:10
In my toy example you can make stuff work by putting `"_self_"` as a first entry in all the `defaults` lists. Then you also have to make `SpecialTrainingConfig` really inherit from `TrainingConfig` (this was described in the text, but the code did not reflect that).
