### ISSUE TITLE
[Bug] Overriding dict using cmd

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#947] opened 2020-09-04 22:08 UTC
# 🐛 Bug
## Description

Can not override a dict from commandline

## Checklist
- [x ] I checked on the latest version of Hydra
- [x ] I created a minimal repro

## To reproduce

** Minimal Code/Config snippet to reproduce **

https://gist.github.com/shagunsodhani/29f8937047fbc10f351a02f1601724ce

** Stack trace/error message **

```
$ python bug/main.py polynomial.x=1 polynomial.y=2 polynomial.z=3

121 (works fine)
```

```
$ python bug/main.py 'polynomial={x:1, y:2, z:3}'

Could not override 'polynomial'. No match in config.
To append to your config use +polynomial={x:1, y:2, z:3}
Key 'x' is not in struct
	full_key: polynomial.x
	reference_type=Any
	object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

```
$ python bug/main.py '+polynomial={x:1, y:2, z:3}'

Could not append to config. An item is already at 'polynomial'.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## System information
- **Hydra Version** :  master
- **Python version** : 3.8
- **Virtual environment type and version** : Conda
- **Operating system** : Ubuntu

**Comment by omry** [comment] 2020-09-04 22:42
I believe this is a duplicate of #946, let me know if you think otherwise.

**Closed by omry** 2020-09-04 22:42 UTC
Labels: bug
