### ISSUE TITLE
[Feature Request] Adding additional directory to the config search path but using code instead of comand line

### ISSUE THREAD

**Issue by hobogalaxy** [facebookresearch/hydra#1259] opened 2021-01-03 16:55 UTC
# 🚀 Feature Request

I know there's a `--config_dir` command line argument, that enables to add an additional directory to the config search path.

Is it possible to the same thing but in code? 
I don't want to pass additional command line parameter every time I run experiment, I would prefer that path to be hardcoded.

If it's not currently possible then it seems like a useful feature.

**Comment by omry** [comment] 2021-01-03 18:05
Thanks for the feature request.
This is somewhat of a duplicate of #274.
I am actually not sure about the final user interface of #274, but it's obvious that there is room for improvement in the capabilities to configure the config search path.

closing as dup.

**Closed by omry** 2021-01-03 18:05 UTC
Labels: enhancement
