### ISSUE TITLE
[Bug] ModuleNotFoundError: no module named 'logging.config'

### ISSUE THREAD

**Issue by bhaprayan** [facebookresearch/hydra#243] opened 2019-10-18 07:05 UTC
# 🐛 Bug

## To reproduce
following tutorial: https://cli.dev/docs/tutorial/logging

** Minimal Code/Config snippet to reproduce **
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import hydra

log = logging.getLogger(__name__)


@hydra.main()
def my_app(_cfg):
    log.info('info level message')
    log.debug('debug level message')
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "logging.py", line 4, in <module>
    import logging
  File "$HOME/workspace/hydra_test/logging.py", line 5, in <module>
    import hydra
  File "$HOME/miniconda3/lib/python3.7/site-packages/hydra/__init__.py", line 2, in <module>
    from . import utils
  File "$HOME/miniconda3/lib/python3.7/site-packages/hydra/utils.py", line 2, in <module>
    import logging.config
ModuleNotFoundError: No module named 'logging.config'; 'logging' is not a package

```

## Expected Behavior
executes successfully (without package import error)

## System information
- 
0.90
- 
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

**Comment by omry** [comment] 2019-10-18 13:08
what version of Python are you using?

**Comment by bhaprayan** [comment] 2019-10-19 14:27
3.7

**Comment by omry** [comment] 2019-10-19 15:11
Hydra is actually tested on Python 3.7 and it works fine. this looks like some kind of system issue.
Can you share more information about your environment?
OS?
Output of "which python"
Output of python --version
Content of PYTHONPATH environment variable?
are you using conda or virtualenv?

This is probably not a bug in Hydra but something that is wrong with your setup.
logging.config is a standard Python module at least since Python 2.7.
https://docs.python.org/2/library/logging.config.html

**Comment by bhaprayan** [comment] 2019-10-21 10:58
```
$ which python
/home/shuby/miniconda3/envs/re/bin/python

$ python --version
Python 3.7.4

$ echo $PYTHONPATH
(empty)

using conda.

**Comment by omry** [comment] 2019-10-21 14:13
Also environment.yaml from:
also attach `conda env export > environment.yaml`
and the output of:
```
$ python
>>> import hydra
>>> import logging
>>> import logging.config
```

Try reproducing with a fresh conda env.
```
conda create -n hydra_test python=3.7
conda activate hydra_test
pip install hydra==0.9.0
...
```
There is a new version of Hydra (0.10.0) but I don't think it should make a difference, so install the same version to make things clearer.
if it works in the clean env, it's either some conflict with something else you have in your conda env - or maybe you are not actually running the python version you think you are.

In any case, I will need minimal repro instructions.

**Comment by omry** [comment] 2019-10-21 20:48
Oh.
Your file is called logging.py, I think it's confusing python and shadowing the logging package.
I am 99% sure this is it, sure enough to close this :)
reopen if renaming it does not fix the problem.

**Closed by omry** 2019-10-21 20:48 UTC
Labels: awaiting_response, bug
