### ISSUE TITLE
[Bug] ConfigKeyError: Key 'defaults' not in <ConfigDataClass>

### ISSUE THREAD

**Issue by karthikprasad** [facebookresearch/hydra#1765] opened 2021-08-12 23:32 UTC
# 🐛 Bug
## Description
Composing structured configs with defaults list results in the above error

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

https://drive.google.com/file/d/193vWa5zkRDBAPtJ55tS9Xlj9bOCEJNl0/view?usp=sharing
**hydra_issue_1765.py**
```python
from dataclasses import dataclass, field
from typing import Any, List, Optional
import hydra
from hydra.core.config_store import ConfigStore
from hydra.utils import instantiate
from omegaconf import OmegaConf, MISSING
from hydra.experimental import initialize, compose

@dataclass
class Foo:
    a: int = 1

@dataclass
class Reducer:
    _target_: str = "__main__.T"
    foo: Foo = MISSING
    defaults: List[Any] = field(default_factory=lambda: [{"/foo": "base_foo"}])

@dataclass
class Trainer:
    _target_: str = "__main__.T"
    reducer: Reducer = MISSING
    defaults: List[Any] = field(default_factory=lambda: [{"/reducer": "base_reducer"}])


class T:
  def __init__(self, **kwargs):
     print(self.__class__, kwargs)

ConfigStore.instance().store(
    name="base_trainer", node=Trainer(), group="trainer"
)
ConfigStore.instance().store(
    name="base_reducer", node=Reducer(), group="reducer"
)
ConfigStore.instance().store(
    name="base_foo", node=Foo(), group="foo"
)

@hydra.main(config_path=None, config_name=None)
def run(cfg):
  print(cfg)

if __name__ == "__main__":
    print(ConfigStore.instance().repo)
    run()
```

To repro, run:
``` bash
python hydra_issue_1765.py +trainer=base_trainer
```

** Stack trace/error message **
```
ConfigKeyError                            Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in load_configuration(self, config_name, overrides, run_mode, from_shell)
    149                 run_mode=run_mode,
--> 150                 from_shell=from_shell,
    151             )

55 frames

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in _load_configuration_impl(self, config_name, overrides, run_mode, from_shell)
    249         cfg = self._compose_config_from_defaults_list(
--> 250             defaults=defaults_list.defaults, repo=caching_repo
    251         )

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in _compose_config_from_defaults_list(self, defaults, repo)
    516                 try:
--> 517                     cfg.merge_with(loaded.config)
    518                 except ValidationError as e:

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in merge_with(self, *others)
    437         except Exception as e:
--> 438             self._format_and_raise(key=None, value=None, cause=e)
    439 

/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
    195             cause=cause,
--> 196             type_override=type_override,
    197         )

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    740             ex.__dict__ = copy.deepcopy(cause.__dict__)
--> 741         _raise(ex, cause)
    742 

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in _raise(ex, cause)
    718         ex.__cause__ = None
--> 719     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
    720 

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in merge_with(self, *others)
    435         try:
--> 436             self._merge_with(*others)
    437         except Exception as e:

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
    459             if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 460                 BaseContainer._map_merge(self, other)
    461             elif isinstance(self, ListConfig) and isinstance(other, ListConfig):

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
    342                     if isinstance(src_value, BaseContainer):
--> 343                         dest_node._merge_with(src_value)
    344                     elif not missing_src_value:

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
    459             if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 460                 BaseContainer._map_merge(self, other)
    461             elif isinstance(self, ListConfig) and isinstance(other, ListConfig):

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
    342                     if isinstance(src_value, BaseContainer):
--> 343                         dest_node._merge_with(src_value)
    344                     elif not missing_src_value:

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
    459             if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 460                 BaseContainer._map_merge(self, other)
    461             elif isinstance(self, ListConfig) and isinstance(other, ListConfig):

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
    377                 else:
--> 378                     dest[key] = src._get_node(key)
    379 

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in __setitem__(self, key, value)
    310             self._format_and_raise(
--> 311                 key=key, value=value, type_override=ConfigKeyError, cause=e
    312             )

/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
    195             cause=cause,
--> 196             type_override=type_override,
    197         )

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    740             ex.__dict__ = copy.deepcopy(cause.__dict__)
--> 741         _raise(ex, cause)
    742 

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in _raise(ex, cause)
    718         ex.__cause__ = None
--> 719     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
    720 

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in __setitem__(self, key, value)
    307         try:
--> 308             self.__set_impl(key=key, value=value)
    309         except AttributeError as e:

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in __set_impl(self, key, value)
    317         key = self._validate_and_normalize_key(key)
--> 318         self._set_item_impl(key, value)
    319 

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _set_item_impl(self, key, value)
    502         input_config = isinstance(value, Container)
--> 503         target_node_ref = self._get_node(key)
    504         special_value = value is None or _is_missing_value(value)

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in _get_node(self, key, validate_access, throw_on_missing_value, throw_on_missing_key)
    464         if validate_access:
--> 465             self._validate_get(key)
    466 

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in _validate_get(self, key, value)
    166                 self._format_and_raise(
--> 167                     key=key, value=value, cause=ConfigAttributeError(msg)
    168                 )

/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
    195             cause=cause,
--> 196             type_override=type_override,
    197         )

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    820 
--> 821     _raise(ex, cause)
    822 

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in _raise(ex, cause)
    718         ex.__cause__ = None
--> 719     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
    720 

ConfigKeyError: Key 'defaults' not in 'Reducer'
    full_key: trainer.reducer.defaults
    object_type=Reducer


The above exception was the direct cause of the following exception:

ConfigCompositionException                Traceback (most recent call last)

<ipython-input-7-1d60f99ac6b0> in <module>()
      1 with initialize(config_path=None):
----> 2      cfg=compose(config_name=None, overrides=["+trainer=base_trainer"])
      3      print(cfg)
      4      instantiate(cfg.trainer, _recursive_=False)

/usr/local/lib/python3.7/dist-packages/hydra/experimental/compose.py in compose(config_name, overrides, return_hydra_config)
     22         config_name=config_name,
     23         overrides=overrides,
---> 24         return_hydra_config=return_hydra_config,
     25     )

/usr/local/lib/python3.7/dist-packages/hydra/compose.py in compose(config_name, overrides, return_hydra_config)
     31         run_mode=RunMode.RUN,
     32         from_shell=False,
---> 33         with_log_configuration=False,
     34     )
     35     assert isinstance(cfg, DictConfig)

/usr/local/lib/python3.7/dist-packages/hydra/_internal/hydra.py in compose_config(self, config_name, overrides, run_mode, with_log_configuration, from_shell)
    566             overrides=overrides,
    567             run_mode=run_mode,
--> 568             from_shell=from_shell,
    569         )
    570         if with_log_configuration:

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in load_configuration(self, config_name, overrides, run_mode, from_shell)
    151             )
    152         except OmegaConfBaseException as e:
--> 153             raise ConfigCompositionException().with_traceback(sys.exc_info()[2]) from e
    154 
    155     def _process_config_searchpath(

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in load_configuration(self, config_name, overrides, run_mode, from_shell)
    148                 overrides=overrides,
    149                 run_mode=run_mode,
--> 150                 from_shell=from_shell,
    151             )
    152         except OmegaConfBaseException as e:

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in _load_configuration_impl(self, config_name, overrides, run_mode, from_shell)
    248 
    249         cfg = self._compose_config_from_defaults_list(
--> 250             defaults=defaults_list.defaults, repo=caching_repo
    251         )
    252 

/usr/local/lib/python3.7/dist-packages/hydra/_internal/config_loader_impl.py in _compose_config_from_defaults_list(self, defaults, repo)
    515                 loaded = self._load_single_config(default=default, repo=repo)
    516                 try:
--> 517                     cfg.merge_with(loaded.config)
    518                 except ValidationError as e:
    519                     raise ConfigCompositionException(

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in merge_with(self, *others)
    436             self._merge_with(*others)
    437         except Exception as e:
--> 438             self._format_and_raise(key=None, value=None, cause=e)
    439 
    440     def _merge_with(

/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
    194             msg=str(cause),
    195             cause=cause,
--> 196             type_override=type_override,
    197         )
    198         assert False

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    739             ex = type_override(str(cause))
    740             ex.__dict__ = copy.deepcopy(cause.__dict__)
--> 741         _raise(ex, cause)
    742 
    743     object_type: Optional[Type[Any]]

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in _raise(ex, cause)
    717     else:
    718         ex.__cause__ = None
--> 719     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
    720 
    721 

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in merge_with(self, *others)
    434     ) -> None:
    435         try:
--> 436             self._merge_with(*others)
    437         except Exception as e:
    438             self._format_and_raise(key=None, value=None, cause=e)

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
    458 
    459             if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 460                 BaseContainer._map_merge(self, other)
    461             elif isinstance(self, ListConfig) and isinstance(other, ListConfig):
    462                 BaseContainer._list_merge(self, other)

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
    341                 if isinstance(dest_node, BaseContainer):
    342                     if isinstance(src_value, BaseContainer):
--> 343                         dest_node._merge_with(src_value)
    344                     elif not missing_src_value:
    345                         dest.__setitem__(key, src_value)

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
    458 
    459             if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 460                 BaseContainer._map_merge(self, other)
    461             elif isinstance(self, ListConfig) and isinstance(other, ListConfig):
    462                 BaseContainer._list_merge(self, other)

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
    341                 if isinstance(dest_node, BaseContainer):
    342                     if isinstance(src_value, BaseContainer):
--> 343                         dest_node._merge_with(src_value)
    344                     elif not missing_src_value:
    345                         dest.__setitem__(key, src_value)

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
    458 
    459             if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 460                 BaseContainer._map_merge(self, other)
    461             elif isinstance(self, ListConfig) and isinstance(other, ListConfig):
    462                 BaseContainer._list_merge(self, other)

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
    376                         dest[key] = src._get_node(key)
    377                 else:
--> 378                     dest[key] = src._get_node(key)
    379 
    380         _update_types(node=dest, ref_type=src_ref_type, object_type=src_type)

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in __setitem__(self, key, value)
    309         except AttributeError as e:
    310             self._format_and_raise(
--> 311                 key=key, value=value, type_override=ConfigKeyError, cause=e
    312             )
    313         except Exception as e:

/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
    194             msg=str(cause),
    195             cause=cause,
--> 196             type_override=type_override,
    197         )
    198         assert False

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    739             ex = type_override(str(cause))
    740             ex.__dict__ = copy.deepcopy(cause.__dict__)
--> 741         _raise(ex, cause)
    742 
    743     object_type: Optional[Type[Any]]

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in _raise(ex, cause)
    717     else:
    718         ex.__cause__ = None
--> 719     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
    720 
    721 

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in __setitem__(self, key, value)
    306     def __setitem__(self, key: DictKeyType, value: Any) -> None:
    307         try:
--> 308             self.__set_impl(key=key, value=value)
    309         except AttributeError as e:
    310             self._format_and_raise(

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in __set_impl(self, key, value)
    316     def __set_impl(self, key: DictKeyType, value: Any) -> None:
    317         key = self._validate_and_normalize_key(key)
--> 318         self._set_item_impl(key, value)
    319 
    320     # hide content while inspecting in debugger

/usr/local/lib/python3.7/dist-packages/omegaconf/basecontainer.py in _set_item_impl(self, key, value)
    501 
    502         input_config = isinstance(value, Container)
--> 503         target_node_ref = self._get_node(key)
    504         special_value = value is None or _is_missing_value(value)
    505 

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in _get_node(self, key, validate_access, throw_on_missing_value, throw_on_missing_key)
    463 
    464         if validate_access:
--> 465             self._validate_get(key)
    466 
    467         value: Optional[Node] = self.__dict__["_content"].get(key)

/usr/local/lib/python3.7/dist-packages/omegaconf/dictconfig.py in _validate_get(self, key, value)
    165                     msg = f"Key '{key}' is not in struct"
    166                 self._format_and_raise(
--> 167                     key=key, value=value, cause=ConfigAttributeError(msg)
    168                 )
    169 

/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
    194             msg=str(cause),
    195             cause=cause,
--> 196             type_override=type_override,
    197         )
    198         assert False

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
    819         ex.ref_type_str = ref_type_str
    820 
--> 821     _raise(ex, cause)
    822 
    823 

/usr/local/lib/python3.7/dist-packages/omegaconf/_utils.py in _raise(ex, cause)
    717     else:
    718         ex.__cause__ = None
--> 719     raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
    720 
    721 

ConfigCompositionException: 
```

## Expected Behavior
The config composition to work correctly.

## System information
- **Hydra Version** :  1.1.0
- **Python version** : 3.7.11
- **Virtual environment type and version** :  Google Colab
- **Operating system** :

**Comment by omry** [comment] 2021-08-13 01:37
Thanks @karthikprasad.
It will really help if you include a paste of a single Python file that is reproducing the problem.
Right now to get there one need to follow the notebook, and start to copy-paste bits and pieces into that file.
Multiple people trying to reproduce this will all have to do it, and they might end up working on a different version of the code.

**Comment by karthikprasad** [comment] 2021-08-13 01:51
@omry , I felt the notebook would be easier to debug as one wouldn't have to copy paste the content and could play around with the code directly. I have edited the original issue with the paste.

**Comment by omry** [comment] 2021-08-13 05:27
Thanks.
While the notebook can be nice to see a repro, it's not helpful to actually debug it.

**Comment by jieru-hu** [comment] 2021-08-17 00:28
Thanks @karthikprasad 

I think what you are trying to do here is to have the defaults list overriding the  structured config you defined. eg,  in `Trainer` you want `base_reducer` to override `reducer: Reducer = MISSING`. This order works in Hydra 1.0 but it has since changed in Hydra 1.1. (the value in config file overrides the default list)

To fix your use case, you can explicitly define the composition order in the defaults list.
```
$ git diff
diff --git a/repro/repro.py b/repro/repro.py
index 0d0578f5c..81b956bf0 100644
--- a/repro/repro.py
+++ b/repro/repro.py
@@ -12,14 +12,14 @@ class Foo:
 
 @dataclass
 class Reducer:
-    defaults: List[Any] = field(default_factory=lambda: [{"/foo": "base_foo"}])
+    defaults: List[Any] = field(default_factory=lambda: ["_self_", {"/foo": "base_foo"}])
     _target_: str = "__main__.T"
     foo: Foo = MISSING
 
 
 @dataclass
 class Trainer:
-    defaults: List[Any] = field(default_factory=lambda: [{"/reducer": "base_reducer"}])
+    defaults: List[Any] = field(default_factory=lambda: ["_self_", {"/reducer": "base_reducer"}])
     _target_: str = "__main__.T"
     reducer: Reducer = MISSING

```

Here is the related doc
https://hydra.cc/docs/advanced/defaults_list
https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order

**Comment by jieru-hu** [comment] 2021-08-18 20:19
Thanks @karthikprasad for the repro! This is an interesting case/bug.

### to get around this

I'm assuming your goal here is to have the defaults list overriding the  structured config you defined. 
eg,  in `Trainer` you want `base_reducer` to override `reducer: Reducer = MISSING`. 
This order works in Hydra 1.0 but it has since changed in Hydra 1.1. (the value in config file overrides the default list)

To fix this, you can explicitly define the composition order in the defaults list.
```
$ git diff
diff --git a/repro/repro.py b/repro/repro.py
index 0d0578f5c..81b956bf0 100644
--- a/repro/repro.py
+++ b/repro/repro.py
@@ -12,14 +12,14 @@ class Foo:
 
 @dataclass
 class Reducer:
-    defaults: List[Any] = field(default_factory=lambda: [{"/foo": "base_foo"}])
+    defaults: List[Any] = field(default_factory=lambda: ["_self_", {"/foo": "base_foo"}])
     _target_: str = "__main__.T"
     foo: Foo = MISSING
 
 
 @dataclass
 class Trainer:
-    defaults: List[Any] = field(default_factory=lambda: [{"/reducer": "base_reducer"}])
+    defaults: List[Any] = field(default_factory=lambda: ["_self_", {"/reducer": "base_reducer"}])
     _target_: str = "__main__.T"
     reducer: Reducer = MISSING

```

Here is the related doc
https://hydra.cc/docs/advanced/defaults_list
https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order


### the bug

Here is an attempt at a minimal repro from omegaconf's point of view

```
from dataclasses import dataclass, field
from typing import Any, List
from omegaconf.basecontainer import BaseContainer
from omegaconf import OmegaConf


@dataclass
class Reducer:
    _target_: str = "__main__.T"
    defaults: List[Any] = field(default_factory=lambda: [{"/foo": "base_foo"}])


src= {'_target_': '???', 'defaults': '???'}
dest={'_target_': '__main__.T'}
dd=OmegaConf.create(dest)
ss=OmegaConf.create(src)
dd._metadata.object_type=Reducer
BaseContainer._map_merge(dd, ss)

# or, the following  line that actually caused the exception
# dd["defaults"] = ss._get_node("defaults") 
```

When composing the configs, Hydra  first turns the `Reducer` dataclass into a `DictConfig`, then [pops](https://github.com/facebookresearch/hydra/blob/7bc2b1ad66da91a12c6158f9413c908b211bff1e/hydra/_internal/config_repository.py#L274) the `defaults` key out to create a defaults list - in which case we end up with a DictConfig object with the typing being `Reducer` but missing one of the fields. When OmegaConf tries to merge `dest` and `src`, it validates that `dest` is of the type `Reducer` - which it isn't (missing `defaults`)



#### suggested fix
I think it might make sense for Hydra to remove `defaults` from  the dataclass and then pass the updated typing to OmegaConf during config composition.  What do you think @omry @Jasha10?

**Comment by karthikprasad** [comment] 2021-08-18 21:03
Thanks @jieru-hu , the work around you suggested does work for this case. However, I don't understand why `_self_` is needed.

I looked at https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order#primary-config-is-a-config-file-with-a-structured-config-schema, but it doesn't apply to my case, does it?

In my example, the primary config is None (not a schema), all that I have is a default list (there is nothing else in the config to override)

**Comment by Jasha10** [comment] 2021-08-18 21:35
@karthikprasad
Currently there is a bug in the code which causes OmegaConf's `ConfigCompositionException` to be raised (as you have seen). For now, adding `_self_` will prevent this exception from being raised.

After we have fixed the bug:
There will no longer be a `ConfigCompositionException`.
In your specific example above, I think you will probably see the behavior if whether you include `_self_` or do not include `_self_`.
With a slightly modified example, I think there would be a behavior difference:
For example, in your `Reducer` dataclass definition, you have `foo: Foo = MISSING`. If instead you had something that is not missing, then you would see a behavior difference between adding `_self_` at the beginning of the defaults list vs not adding `_self_`.
This is because (1) adding `_self_` at the beginning means that the `base_foo` gets merged into `Reducer.foo`, while not adding `_self_` means that `Reducer.foo` gets merged into `base_foo`, and (2) MISSING gets treated specially by OmegaConf's merge operation, so if `Reducer.foo == MISSING` then you will see the same output whether the `_self_` value is included or not.

> #### suggested fix
> 
> I think it might make sense for Hydra to remove `defaults` from the dataclass and then pass the updated typing to OmegaConf during config composition. What do you think @omry @Jasha10?

So in your example above, Hydra would remove the `defaults` key from the `ss` DictConfig before performing the merge? That makes sense to me (given that `defaults` is being treated by Hydra as a reserved keyword).
I'm hoping that any info contained in `ss.defaults` will be assimilated into the defaults tree by other parts of Hydra's internals -- we don't want loss of information when deleting `ss.defaults`.

Zooming out:
The Reducer _dataclass_ has a `defaults` key, but the Reducer _structured config_ has had its `defaults` key surgically removed, so there is a mismatch between the two schemas.

Yet the structured config still retains reference to the original dataclass (via the `object_type` and/or `ref_type` metadata), so collision between these two schemas (like what happened here) is a real possibility... Not sure what can be done about it besides carefully patching collisions if they occur :)

**Comment by Jasha10** [comment] 2021-08-18 21:36
> #### suggested fix
> 
> I think it might make sense for Hydra to remove `defaults` from the dataclass and then pass the updated typing to OmegaConf during config composition. What do you think @omry @Jasha10?

So in your example above, Hydra would remove the `defaults` key from the `ss` DictConfig before performing the merge? That makes sense to me (given that `defaults` is being treated by Hydra as a reserved keyword).
I'm hoping that any info contained in `ss.defaults` will be assimilated into the defaults tree by other parts of Hydra's internals -- we don't want loss of information when deleting `ss.defaults`.

Zooming out:
The Reducer _dataclass_ has a `defaults` key, but the Reducer _structured config_ has had its `defaults` key surgically removed, so there is a mismatch between the two schemas.

Yet the structured config still retains reference to the original dataclass (via the `object_type` and/or `ref_type` metadata), so collision between these two schemas (like what happened here) is a real possibility... Not sure what can be done about it besides carefully patching collisions if they occur :)

**Comment by karthikprasad** [comment] 2021-08-18 21:52
Thanks @Jasha10 , that explanation was helpful in resolving my confusion.

**Comment by omry** [comment] 2021-08-18 22:40
> I think it might make sense for Hydra to remove defaults from the dataclass and then pass the updated typing to OmegaConf during config composition. What do you think @omry @Jasha10?

Changing the dataclass feels dangerous. I am not even sure it's possible.
Even if it is, it will likely have unexpected consequences (the same dataclass might be used to compose later and then there will be no defaults list).

I am checking if another approach might solve it. more on that later.

**Closed** 2021-09-14 16:59 UTC
Labels: bug
