### ISSUE TITLE
[Bug] Override config group option default parameters

### ISSUE THREAD

**Issue by alexandreMayerowitz** [facebookresearch/hydra#1233] opened 2020-12-23 11:41 UTC
# 🐛 Bug
## Description
Hello guys,

I do not know if this is a bug or a misunderstanding on my side but I definitely try to override a config group option default parameters from a config file but without any success.

## Checklist
- [X] I checked on the latest version of Hydra

## To reproduce

**Minimal Code/Config snippet to reproduce**
Python file : **main.py**

```python
# Standard libraries
from dataclasses import dataclass

# Third-party libraries
import hydra
from hydra.core.config_store import ConfigStore
from hydra.types import TargetConf


@dataclass
class AlgorithmConfig(TargetConf):
    _target_: str = 'test'
    mode: str = 'max'


ConfigStore.instance().store(group='tune/algorithm', name='default', node=AlgorithmConfig)


@dataclass
class TuneConfig:
    algorithm: AlgorithmConfig = AlgorithmConfig()


ConfigStore.instance().store(group='tune', name='default', node=TuneConfig)


@dataclass
class Config:
    test: bool = True
    tune: TuneConfig = TuneConfig()


# Stores config node into the repository
ConfigStore.instance().store(name='config', node=Config)


@hydra.main(config_path='conf', config_name='config')
def main(config: Config) -> None:
    """Main function."""
    print(config)
    print(config.tune.algorithm)


if __name__ == "__main__":
    main()
```

And the config file **conf/config.yaml:** 

```yaml
defaults:
  - tune: default
  - tune/algorithm: default

test: False
tune:
  algorithm:
    mode: 5
```

**Stack trace/error message**
```
{'test': False, 'tune': {'algorithm': {'_target_': 'test', 'mode': 'max'}}}
{'_target_': 'test', 'mode': 'max'}
```

We clearly see that the **test** node is properly overriden with **False value**.
But if we have a look at the **tune/algorithm** group which has **default** as config group option, I can not override the **mode** parameter like this.
Do you know if I'm doing something wrong or if hydra does not allow this for the moment?

## Expected Behavior

What I expect from this short example is to override the **mode** parameter and output something like this: 

```
{'test': False, 'tune': {'algorithm': {'_target_': 'test', 'mode': 5}}}
{'_target_': 'test', 'mode': 5}
```

## System information
- **Hydra Version** :  1.0.4
- **Python version** : 3.8.5
- **Virtual environment type and version** : Conda environment 
- **Operating system** : Mac OS X

**Comment by omry** [comment] 2020-12-23 16:36
The defaults list is for specifying configs. Such configs can be yaml files or configs stored into the ConfigStore.
you do not have a config `tune/algorithm`.

There is a bit of misunderstanding here, please go carefully over the basic tutorial and again and then over the structured configs tutorial.
Feel free to ask followup questions here after you have done that.

Closing as this is not a bug.

**Comment by alexandreMayerowitz** [comment] 2020-12-23 18:11
Thanks omry for your answer. 
Maybe I am not clear with my issue.

When I have a look at that example (Ax plugin) : https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_ax_sweeper/example/conf/config.yaml
This is acting exactly the way I want. You specify a default config group option for the `hydra/sweeper` group, i.e. ax.
Then in the core of the config, you can override the default ax sweeper config, following that struct: https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_ax_sweeper/hydra_plugins/hydra_ax_sweeper/config.py

Why is this working for the ax sweeper plugin but not in my example, with the `tune/algorithm` group ?

Thanks in advance for your help.

**Comment by omry** [comment] 2020-12-24 00:28
OHH.
I think I understand.
Take a look at the composition trace (--info).
You will see that the default lists entries are coming after your config.
This is the behavior in Hydra 1.0.

To get your config to override the things in the defaults list, you need to split it into two.
something like:

config.yaml
```yaml
defaults:
  - tune: default
  - tune/algorithm: default
  - config_overrides
```

config_overrides.yaml:
```yaml
test: False
tune:
  algorithm:
    mode: 5
```
This way the composition order will be what you are expecting.
I am planning to change the default composition order to match your expectation in Hydra 1.1.
There will also be a facility to control that explicitly (adding an new element called `_self_` to the defaults list).

**Comment by omry** [comment] 2020-12-24 00:30
Also, do not extend TargetConf.

**Comment by omry** [comment] 2020-12-24 00:43
Try the attached version.

[1.zip](https://github.com/facebookresearch/hydra/files/5737588/1.zip)

**Comment by alexandreMayerowitz** [comment] 2020-12-24 11:23
Lovely, this is exactly the workaround I need for the moment.
Thank you very much omry for your time and help.
The --info option is marvelous, I was suspecting something like that in the composition order but without any assurance. This confirms the theory.

Ok for Hydra 1.1. Indeed, I think that changing the default composition order will be clearer for users. When do you expect the new release to happen?

Thanks a lot!

**Comment by omry** [comment] 2020-12-24 17:02
You can follow the [milestone for 1.1](https://github.com/facebookresearch/hydra/milestone/5). there is no set date but it's pretty far out (guessing multiple months).

Changing the default composition order is delicate and can be a breaking change for some apps. I am still thinking about the best way to do it.

Take a look at #1170 and the linked design doc to see the biggest changes coming in Hydra 1.1 (related to the issue you ran into).

**Closed by omry** 2020-12-24 17:02 UTC
Labels: bug
