### ISSUE TITLE
[Feature Request]Using a launcher in a single run setup

### ISSUE THREAD

**Issue by jbaczek** [facebookresearch/hydra#2074] opened 2022-03-07 15:50 UTC
# 🚀 Feature Request

An ability to use a custom launcher without a custom sweeper and multirun.

## Motivation

Related issue: https://github.com/facebookresearch/hydra/issues/2038 \
Pytorch supports training on distributed systems, but it's default launching utility, `torchrun `, first spawns processes and then launches a script which results in initializing hydra in every process leading to conflicts. The solution would be to use custom launcher which implements `torchrun` utility but calls a function that is wrapped by `hydra.main` after hydra initialization. \
Currently it is possible to use a launcher only via a sweeper which is called only in multirun setting. I don't want to perform any sweeps (unless I explicitly state it in command line adding for example `hydra/sweeper=optuna`) and I consider my job a single run.

## Pitch

I want an ability to use launchers in a single run setup.

**Comment by Jasha10** [comment] 2022-03-07 19:22
Thanks @jbaczek.

As far as design is concerned, I believe that currently overriding `hydra/launcher` in the defaults list has no effect if `--multirun` mode is not used.
We should change this so that the default setting for `hydra/launcer` is respected in single-run mode.

**Comment by d-miketa** [comment] 2022-03-15 10:53
I'd also like to use a custom launcher in a single run, in my case to start a Prefect flow.

**Comment by Jasha10** [comment] 2022-03-24 18:14
Cross-link to issue #851 which could be considered a duplicate of this issue.

**Comment by pixelb** [comment] 2022-03-29 16:27
Closing as tracked in #851

**Closed by pixelb** 2022-03-29 16:27 UTC
Labels: enhancement, launchers
