### ISSUE TITLE
[Feature Request]  Avoid Logging Error for Distributed Training

### ISSUE THREAD

**Issue by qywu** [facebookresearch/hydra#547] opened 2020-04-20 06:05 UTC
# 🚀 [Feature Request] Avoid Logging Error for Distributed Training

## Motivation

The current implementation doesn't work well with `python torch.distributed.launch`. The main problem is with `configure_log` and `_save_config` in `hydra/core/utils.py`, which will try to write logs to a file. However, this will cause problems when multiple processes are writing to the same file.

## Pitch

Maybe one solution is to use the environmen variable `os.environ["RANK]"` which is used in `torch.distributed.launch` to identify the rank of the process and only configure logging for the master rank.

Or an alternative is to use a file lock to ensure the file is not corrupted.

**Comment by omry** [comment] 2020-04-20 06:56
1. Without a minimal example I can't reproduce this and understand what it is that you are actually doing.

2. Taking a guess, you should customize the logging filename and the hydra output directory.
See the [this](https://hydra.cc/docs/configure_hydra/logging/) and this [example](https://github.com/facebookresearch/hydra/tree/master/examples/configure_hydra/logging) of log customization.

You can change the filename to depend on  the rank. [here](https://github.com/facebookresearch/hydra/blob/master/hydra/conf/hydra/job_logging/default.yaml) is the logging config (you can also see it in the Hydra config if you use `--cfg hydra`).

try overriding
```yaml
filename: ${hydra.job.name}.log
```
to something like 
```yaml
filename: ${hydra.job.name}_${env:RANK}.log
```

Closing this as invalid, but I am happy to answer followup questions.

**Closed by omry** 2020-04-20 06:56 UTC
Labels: enhancement, invalid
