### ISSUE TITLE
[Feature Request] Multirun with config groups

### ISSUE THREAD

**Issue by tueboesen** [facebookresearch/hydra#2625] opened 2023-03-27 09:51 UTC
# 🚀 Feature Request

I am new to hydra and still testing out whether it is a viable option for me, so I could easily be wrong and this feature already exist, but if so I haven't been able to find it in the documentation.

I would like the option of specifying whether a multirun is using combinatorics over the multirun parameters or whether they are groups of parameters.

If for example we have:
```yaml
hydra:
    mode: MULTIRUN
    sweeper:
        params:
          +n: 5,10,15
          +a: 0.5, 0.7, 0.9
```

Then that would currently result in 9 different jobs trying out all combinations as far as I understand. What I would like is the ability to specify that these parameters should be grouped as ordered.

So I want an option where I can take the same parameters and return only 3 jobs. with `(n=5,a=0.5)`, `(n=10, a=0.7)` and `(n=15, a=0.9)`

## Motivation

Having something like this would enable me to easily create a single yaml file with all the jobs needed to produce all the results in a paper. Which would be great for reproduceability 

## Pitch

The cleanest way to implement something like this would probably be to have an optional keyword somewhere in the sweeper that details whether the sweeper runs combinatoric combination or config groups.
In case of config groups there should probably be some logic to check that the length of each of the parameters are identical 

More advanced modes that enables some combinations of the two different modes could probably also exist, but I haven't thought much about that.

**Comment by Jasha10** [comment] 2023-04-18 14:47
@tueboesen I am going to close this feature request as a duplicate of https://github.com/facebookresearch/hydra/issues/1258. Please see the workarounds/strategies discussed on that thread.

**Closed as completed by Jasha10** 2023-04-18 14:47 UTC
Labels: enhancement
