### ISSUE TITLE
[Bug] Customizing logging: creates empty folder if log to filesystem is disabled

### ISSUE THREAD

**Issue by svenw3** [facebookresearch/hydra#264] opened 2019-10-28 09:07 UTC
# 🐛 Bug

I try to deactive the logging on file system as described by: https://cli.dev/docs/configure_hydra/logging 

This provides error [1] (see stack trace). 

After changing it into  https://github.com/facebookresearch/hydra/tree/master/examples/configure_hydra/logging, an empty folder is created for each run (outputs/{date}/{time}). 

## To reproduce

conf/hydra/job_logging/custom.yaml:
```
hydra:
  # python logging configuration for tasks
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]

    disable_existing_loggers: False

```
** Stack trace/error message **
Error 1: Sample code from https://cli.dev/docs/configure_hydra/logging
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    sys.exit(experiment())
  File "*.pyenv/versions/3.7.4/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "*.pyenv/versions/3.7.4/lib/python3.7/site-packages/hydra/_internal/utils.py", line 56, in run_hydra
    hydra.run(overrides=args.overrides)
  File "*.pyenv/versions/3.7.4/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 114, in run
    job_subdir_key=None,
  File "*.pyenv/versions/3.7.4/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 85, in run_job
    configure_log(config.hydra.job_logging, config.hydra.verbose)
  File "*.pyenv/versions/3.7.4/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 22, in configure_log
    logging.config.dictConfig(conf)
  File "*.pyenv/versions/3.7.4/lib/python3.7/logging/config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "*.pyenv/versions/3.7.4/lib/python3.7/logging/config.py", line 495, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version
```

## Expected Behavior
I would expect that "Outputs only to stdout (no log file)" does not create any folders. 

## System information
- hydra-core: 0.10.0
- python: 3.7.4
- MacOS

**Comment by omry** [comment] 2019-10-28 11:43
1. The directory you get is not empty, it has a .hydra sub directory with the config and other things.
2. The error you are seeing is probably because you are missing a version field in your dictionary.

So far everything is as designed, is there an actual bug here?

**Comment by svenw3** [comment] 2019-10-28 12:07
ok, you're right, there is a hidden folder, sorry!

However, in my opinion the problem is the folder itself, regardless whether there is sth. in it or not. According to the tutorial (https://cli.dev/docs/configure_hydra/logging/) it should "Outputs only to stdout (no log file)". So as mentioned, I would expect that it does not create any files/folders, log its configuration on file system, etc.

If it is intended to output the config.yaml, hydra.yaml and overrides.yaml this won't be a bug but rather a feature request. In my case it is not possible to write anything on the file system, but nevertheless I'd like to use hydra to create different configurations.

**Comment by omry** [comment] 2019-10-28 12:11
The tutorial is talking about creating a log file, not other files Hydra is creating.
This is an example of how to customize the logging, not how to prevent the creation of output directories per run.
You can do that, to some extent by customizing the output directory pattern to something static (see https://cli.dev/docs/configure_hydra/workdir).
If you wish to file a feature request to allow no output files to be created file it and we can discuss the use case.
I am closing this one, there is no bug here.

**Closed by omry** 2019-10-28 12:11 UTC
Labels: bug

**Comment by svenw3** [comment] 2019-10-28 12:13
Ok, thanks for your time!
