### ISSUE TITLE
[Bug] Multirun startup tends to become quite slow for large sweeps.

### ISSUE THREAD

**Issue by TommasoBendinelli** [facebookresearch/hydra#1324] opened 2021-01-22 10:40 UTC
# 🐛 Bug
## Checklist
- [ X] I checked on the latest version of Hydra
- [ X] I created a minimal repro (See [this](https:// .com/help/minimal-reproducible-example) for tips).

## To reproduce
I have create the following basic yaml file 
```
defaults:
  - parameters: case1
  - parameters/additional: subvalues1

hydra:
  overrides:
      task:
      - parameters=case1,case2,case3
      - +num=range(0,2)
```

associated with this python script:
```
import hydra
import json


@hydra.main(config_path="conf", config_name="config")
def main(cfg):
    print(cfg)


if __name__ == "__main__":
    main()


```
When I change num from range(0,2) to range(0,100), takes much more time start (i.e. from less than one second to about one minute)

## Expected Behavior
I would expect a much less slow down.

## System information
- Hydra 1 :  
- Python 3.8* : 
- VirtualEnv: virtualenv : 
- Operating System: Ubuntu 20.04 :

**Comment by jieru-hu** [comment] 2021-01-22 17:24
Thanks for reporting.

Could you provide the exact version info in `System Information`? from commands like
```
pip freeze | grep hydra
python --version
```

Also a `time python my_app.py` would be helpful too. Thanks.

**Comment by jieru-hu** [comment] 2021-01-22 19:22
For each sweep,  Hydra is generates the configs for all sweep jobs in the beginning which helps surface any potential config issue early on. 

You can try to add a [max_batch_size](https://github.com/facebookresearch/hydra/blob/44b843629e7f01e40b853bcdf66d7fa2645365fd/hydra/_internal/core_plugins/basic_sweeper.py#L39-L42) to your sweeper config to change the default behavior. 

(thanks to @omry who pointed this out offline)

**Comment by TommasoBendinelli** [comment] 2021-01-23 06:22
Additional System Informations:

```
(env) tes@tes-MS-7C59:~/repos/testing_out$ pip freeze | grep hydra
hydra-ax-sweeper==1.1.0rc1
hydra-core==1.0.4
hydra-nevergrad-sweeper==1.1.0rc1
```

Python version: 3.8.6

**Comment by omry** [comment] 2021-01-26 20:31
Hydra is validating the configs for each of the launched jobs before they start. This takes a time linear to the number of jobs in the batch.

1. Using max_batch_size parameter will amortize this cost better by (For example ,you can set it to 10: `hydra.sweeper.max_batch_size=10`)
2. OmegaConf 2.1 (that goes with Hydra 1.1) has some significant optimizations, speeding up config composition. Please try the lastest 1.1.0 dev release.

**Comment by omry** [comment] 2021-01-27 23:36
Closing as this is not a bug. feel free to continue the discussion.

**Closed by omry** 2021-01-27 23:36 UTC
Labels: bug

**Comment by jccalvojackson** [comment] 2022-12-02 08:26
maybe adding a tqdm progress bar on the checks?
