### ISSUE TITLE
[Feature Request] Allow for list of config groups to include

### ISSUE THREAD

**Issue by erip** [facebookresearch/hydra#556] opened 2020-04-26 17:25 UTC
# 🚀 Feature Request

Hydra should allow a list of config groups t

## Motivation

Consider the case of including some set of metrics in an experiment. It would be nice to allow a user to specify these:

```
defaults:
    - metrics
        - accuracy
        - loss
```

with the ability to override them.

## Pitch

This is fairly different from what hydra typically does, which seems to be oriented toward testing _mutually exclusive classes of configuration groups_ (e.g., mysql vs. postgres), but this would allow for more flexible overriding of user-defined list of attributes; for instance: in the above example: 

```
./my_app.py metrics="[accuracy, loss, wps]"
```

If defaults need to be changed within these config groups: 

```
./my_app.py metrics="[accuracy, loss, wps]" "metrics[0].class=some.custom.AccuracyClass"
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

Yes.

## Additional context

There may be some clever way to achieve this already, but I don't believe it's covered in the documentation currently.

**Comment by omry** [comment] 2020-04-26 17:34
Duplicate of #499

**Closed by omry** 2020-04-26 17:34 UTC
Labels: enhancement

**Comment by omry** [comment] 2020-04-26 17:37
Thanks for the suggestion, there is already a very similar one (#499).
This is a very fundamental change and will require some thinking, as well as some user facing changes that I want to make sure makes sense.

**Comment by omry** [comment] 2020-04-26 17:38
In the mean time, you can emulate this using OmegaConf merge functionality.

**Comment by erip** [comment] 2020-04-26 17:46
Ah, I didn't look hard enough - sorry about that! I'll drop down into OmegaConf for now and if we can move up a level to hydra later, that would be awesome. 👍 thanks for the quick response!
