### ISSUE TITLE
[Question] Override default hydra configuration

### ISSUE THREAD

**Issue by ZachariahPang** [facebookresearch/hydra#1646] opened 2021-05-31 03:05 UTC
For organizing experiments (using the example from the [doc](https://hydra.cc/docs/next/patterns/configuring_experiments/#internaldocs-banner)), we could override the defaults values in file
`experiment/nglite.yaml` with
```
# @package _global_
defaults:
  - override /db: sqlite
  - override /server: nginx
  
server:
  port: 8080
```

Is it possible to override the hydra config within the same file?
I tried
```
# @package _global_
defaults:
  - override /hydra: some_config
``` 
but would result an error `Could not override 'hydra'.
Did you mean to override hydra?.`

**Comment by Jasha10** [comment] 2021-06-01 17:18
Hi @ZachariahPang,

Please take a look at [examples/configure_hydra/custom_help/conf/config.yaml](https://github.com/facebookresearch/hydra/blob/1.0_branch/examples/configure_hydra/custom_help/conf/config.yaml) if you are using Hydra 1.0, or at [the more recent version](https://github.com/facebookresearch/hydra/blob/v1.1.0.rc1/examples/configure_hydra/custom_help/conf/config.yaml) if you are using Hydra 1.1.0.rc1.

**Comment by jieru-hu** [comment] 2021-06-01 20:59
@ZachariahPang could you provide more info on what `some_config ` looks like here? as Jasha commented above, overriding a specific hydra config group is supported in Hydra 1.1rc.

**Comment by omry** [comment] 2021-06-02 16:56
1. Please provide a zip file containing a minimal runnable example and repro instructions and expected behavior.
2. Please pastebin the output of `--info config` and the output of `--config all`.

**Comment by omry** [comment] 2021-06-07 19:19
Closing, feel free to reopen and provide the requested info.

**Closed by omry** 2021-06-07 19:19 UTC
Labels: question
