### ISSUE TITLE
[Bug] submitit launcher doesnt work with dynamically defined enums

### ISSUE THREAD

**Issue by alexeib** [facebookresearch/hydra#1156] opened 2020-11-19 01:54 UTC
this works:
```python fairseq_cli/hydra_train.py --multirun  distributed_training.distributed_world_size=2 checkpoint.save_dir=/checkpoint/abaevski/tmp task.data=/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/ +optimization.update_freq='[2]' --config-path /private/home/abaevski/fairseq-py/examples/wav2vec/config/pretraining --config-name wav2vec2_large_librivox```

this does not work:
```python fairseq_cli/hydra_train.py --multirun hydra/launcher=submitit_slurm hydra.launcher.cpus_per_task=80 hydra.launcher.gpus_per_node=8 hydra.launcher.tasks_per_node=1 hydra.launcher.nodes=2 hydra.launcher.partition=dev hydra.launcher.mem_gb=400 distributed_training.distributed_world_size=16 checkpoint.save_dir=/checkpoint/abaevski/tmp task.data=/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/ +optimization.update_freq='[2]' --config-path /private/home/abaevski/fairseq-py/examples/wav2vec/config/pretraining --config-name wav2vec2_large_librivox```

error is:
```
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration
    run_mode=run_mode,
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 804, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, system_list)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 772, in merge_defaults_list_into_config
    merged_cfg.merge_with(job_cfg)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 327, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/_utils.py", line 610, in format_and_raise
    _raise(ex, cause)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/_utils.py", line 591, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 325, in merge_with
    self._merge_with(*others)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 343, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 290, in _map_merge
    dest_node._merge_with(src_value)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 343, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 301, in _map_merge
    dest._format_and_raise(key=key, value=src_value, cause=e)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/_utils.py", line 675, in format_and_raise
    _raise(ex, cause)
  File "/private/home/abaevski/.conda/envs/fairseq-fp16-20200821/lib/python3.6/site-packages/omegaconf/_utils.py", line 591, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: Value json (Choices) is not a valid input for <enum 'Choices'>
        full_key: common.log_format
        reference_type=CommonConfig
        object_type=CommonConfig
```

common.logformat is defined as follows:
```python
log_format: Optional[LOG_FORMAT_CHOICES] = field(
        default=None, metadata={"help": "log format to use"}
    )
```
where LOG_FORMAT_CHOICES is `LOG_FORMAT_CHOICES = ChoiceEnum(["json", "none", "simple", "tqdm"])`

and ChoiceEnum is

```
class StrEnum(Enum):
    def __str__(self):
        return self.value

    def __eq__(self, other: str):
        return self.value == other

    def __repr__(self):
        return self.value

    def __hash__(self):
        return hash(str(self))


def ChoiceEnum(choices: List[str]):
    """return the Enum class used to enforce list of choices"""
    return StrEnum("Choices", {k: k for k in choices})
```

(you can find these here: https://github.com/pytorch/fairseq/blob/master/fairseq/dataclass/constants.py)

**Comment by alexeib** [comment] 2020-11-19 02:02
actually this fails too and is easier to repro:
```
python fairseq_cli/hydra_train.py --multirun hydra/launcher=submitit_local hydra.launcher.cpus_per_task=80 hydra.launcher.gpus_per_node=2 hydra.launcher.tasks_per_node=1  hydra.launcher.mem_gb=400 distributed_training.distributed_world_size=16 checkpoint.save_dir=/checkpoint/abaevski/tmp task.data=/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/ +optimization.update_freq='[2]' --config-path /private/home/abaevski/fairseq-py/examples/wav2vec/config/pretraining --config-name wav2vec2_large_librivox
```

**Comment by alexeib** [comment] 2020-11-19 02:34
maybe its because when we run this without submit it we do this as the first thing:

cfg = OmegaConf.create(OmegaConf.to_container(cfg, resolve=True, enum_to_str=True))

?

**Comment by alexeib** [comment] 2020-11-19 03:06
whats strange is if i add

a print here:
```
@staticmethod
359     def validate_and_convert_to_enum(
360         enum_type: Type[Enum], value: Any
361     ) -> Optional[Enum]:
362         if value is None:
363             return None
364
365         if not isinstance(value, (str, int)) and not isinstance(value, enum_type):
366             print(type(value), enum_type, isinstance(value, enum_type))
367             raise ValidationError(
368                 f"Value $VALUE ($VALUE_TYPE) is not a valid input for {enum_type}"
369             )
```

i get

<enum 'Choices'> <enum 'Choices'> False

**Comment by alexeib** [comment] 2020-11-19 03:30
the ids of those 2 classes are different because somewhere submit it loads something from a pickle and ends up with a different type of class

**Comment by omry** [comment] 2020-11-19 04:57
Submitit recently switched to cloudpickle for all serialization, but looks like they messed up the release.

Using a minimal repro with a standard enum, things seems to work for me.
```diff
$ git diff
diff --git a/examples/tutorials/structured_configs/4_defaults/my_app.py b/examples/tutorials/structured_configs/4_defaults/my_app.py
index c1b3fbb65..7712c5742 100644
--- a/examples/tutorials/structured_configs/4_defaults/my_app.py
+++ b/examples/tutorials/structured_configs/4_defaults/my_app.py
@@ -6,7 +6,11 @@ from omegaconf import MISSING, OmegaConf  # Do not confuse with dataclass.MISSIN
 
 import hydra
 from hydra.core.config_store import ConfigStore
+from enum import Enum
 
+class Color(Enum):
+    red = 1
+    green = 2
 
 @dataclass
 class MySQLConfig:
@@ -15,6 +19,7 @@ class MySQLConfig:
     port: int = 3306
     user: str = "omry"
     password: str = "secret"
+    color: Color = Color.red
```

```
~/dev/hydra/examples/tutorials/structured_configs/4_defaults$ python my_app.py hydra/launcher=submitit_local db.color=green -m
[2020-11-18 20:56:33,013][HYDRA] Submitit 'local' sweep output dir : multirun/2020-11-18/20-56-32
[2020-11-18 20:56:33,014][HYDRA]        #0 : db.color=green
```

But only if I install submitit from github. Otherwise I am getting a completely different error.

1. Try to install submitit from master. does it help?
If it does not help:
2. Since your dynamic enum is not officially supported (or tested), can you try to create a minimal repro (Hydra + the submitit plugin) using a standard enum and see if you still see it? You can base it one of of the examples in the Structured config tutorial.

I filed an [issue](https://github.com/facebookincubator/submitit/issues/35) against submitit to update their release.

**Comment by alexeib** [comment] 2020-11-21 21:12
i tried installing submitit from github (`pip install 'git+https://github.com/facebookincubator/submitit@master#egg=submitit'`) but it fails in teh same way. it still has things about pickling in the out log:
```
submitit INFO (2020-11-21 13:10:52,164) - Starting with JobEnvironment(job_id=41785, hostname=devfair0179, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2020-11-21 13:10:52,164) - Loading pickle: /private/home/abaevski/fairseq-py/multirun/2020-11-21/13-10-49/.submitit/41785/41785_submitted.pkl
submitit ERROR (2020-11-21 13:10:54,604) - Submitted job triggered an exception
2020-11-21 13:10:54 | ERROR | submitit | Submitted job triggered an exception
```

**Comment by alexeib** [comment] 2020-11-21 22:13
on further investigation this does not happen with the basic enum. however for our use case, due to having to backward compatibility requirements, we cannot use standard enums. 

here is a repro. 
key ingridients: 
- define enum in a different file that gets imported, 
- define main function in a different file
- set the default value in a config to an actual instance of a data class

```
--- i/examples/tutorials/structured_configs/4_defaults/my_app.py
+++ w/examples/tutorials/structured_configs/4_defaults/my_app.py
@@ -6,7 +6,7 @@ from omegaconf import MISSING, OmegaConf  # Do not confuse with dataclass.MISSIN

 import hydra
 from hydra.core.config_store import ConfigStore
-
+from constants import LOG_FORMAT_CHOICES

 @dataclass
 class MySQLConfig:
@@ -15,6 +15,7 @@ class MySQLConfig:
     port: int = 3306
     user: str = "omry"
     password: str = "secret"
+    log_format: LOG_FORMAT_CHOICES = "tqdm"


 @dataclass
@@ -29,7 +30,7 @@ class PostGreSQLConfig:

 defaults = [
     # config group name db will load config named mysql
-    {"db": "mysql"}
+#    {"db": "mysql"}
 ]


@@ -39,7 +40,7 @@ class Config:
     defaults: List[Any] = field(default_factory=lambda: defaults)

     # Hydra will populate this field based on the defaults list
-    db: Any = MISSING
+    db: MySQLConfig = MISSING


 cs = ConfigStore.instance()
@@ -48,10 +49,3 @@ cs.store(group="db", name="postgresql", node=PostGreSQLConfig)
 cs.store(name="config", node=Config)


-@hydra.main(config_name="config")
-def my_app(cfg: Config) -> None:
-    print(OmegaConf.to_yaml(cfg))
-
-
-if __name__ == "__main__":
-    my_app()
```

```
cat constants.py                                              14:12:49
from typing import List
from enum import Enum

class Color(Enum):
    red = 1
    green = 2

class StrEnum(Enum):
    def __str__(self):
        return self.value

    def __eq__(self, other: str):
        return self.value == other

    def __repr__(self):
        return self.value

    def __hash__(self):
        return hash(str(self))


def ChoiceEnum(choices: List[str]):
    """return the Enum class used to enforce list of choices"""
    return StrEnum("Choices", {k: k for k in choices})

LOG_FORMAT_CHOICES = ChoiceEnum(["json", "none", "simple", "tqdm"])
```
cat main.py                                                   14:12:51
import hydra
from my_app import Config
from omegaconf import OmegaConf

@hydra.main(config_name="config")
def my_app(cfg: Config) -> None:
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    my_app()
```

```

`python main.py hydra/launcher=submitit_local +db=mysql db.log_format=json -m`
output:
```
omegaconf.errors.ValidationError: Value tqdm (Choices) is not a valid input for <enum 'Choices'>
	full_key: db.log_format
	reference_type=MySQLConfig
	object_type=MySQLConfig
```

**Comment by omry** [comment] 2020-11-22 00:37
Thanks for the repro, we will take a look.

Did you try to upgrade submitit as I suggested? they released a version that properly uses cloudpickle.
This is EXACTLY the kind of thing cloudpickle is likely to handle correctly where standard pickle does not.

Also, can you explain your backward compatibility requirements?


> i am not sure how to proceed. so far i can think of:
a) fix it in hydra / submitit
b) hack hydra/submitit in order to be able to use submitit with fairseq, but then always have to use hacked hydra/submitit version
c) write our own launcher?
what would you suggest we do in this case?

I don't want to make suggestions before we had a time to try to understand what is happening here.

**Comment by omry** [comment] 2020-11-22 00:44
Ah, I missed your comment about submitit.
It still pickles, it just uses cloudpickle instead of the standard pickle to serialize.

**Comment by alexeib** [comment] 2020-11-22 02:39
if i patch omegaconf nodes.py like so:

```python
358     @staticmethod
359     def validate_and_convert_to_enum(
360         enum_type: Type[Enum], value: Any
361     ) -> Optional[Enum]:
362         if value is None:
363             return None
364
365         if str(type(value)) == str(enum_type):
366             enum_type = type(value)
367
368         if not isinstance(value, (str, int)) and not isinstance(value, enum_type):
369             raise ValidationError(
370                 f"Value $VALUE ($VALUE_TYPE) is not a valid input for {enum_type}"
371             )
```

everything works now. its not a great fix but at least theres no errors after getting past this one

**Comment by omry** [comment] 2020-11-22 03:07
Can you explain your backward compatibility requirements?
It seems to me like one workaround here is to annotate the field as a string instead of your magic Enum and do the validation yourself.

**Comment by alexeib** [comment] 2020-11-22 03:12
backward compat requirements is that we previously used argparse enums and limited what can be passed in with the "choices=..." arg. We want to still be able to a) generate these choices for argparse, b) populate configs with strings rather than int-based enum values, c) be able to correctly convert previous argparse based configs stored in checkpoints or created in the old entrypoints that would end up having a string value, while still limiting the choices of what people can provide for these options in hydra configs

actually, i found a workaround:

```python
class StrEnumMeta(EnumMeta):
    @classmethod
    def __instancecheck__(cls, other):
        return "enum" in str(type(other))


class StrEnum(Enum, metaclass=StrEnumMeta):
...
```

**Comment by omry** [comment] 2020-11-22 17:20
First of all, great that you have found a workaround.
If I understand it correctly, wouldn't that be better?
```
class StrEnumMeta(EnumMeta):
    @classmethod
    def __instancecheck__(cls, other):
        return isinstance(other, Enum) and type(cls).__name__ == type(other).__name__
```
?

### Backward compatibility requirements

> a) generate these choices for argparse
I think you can still do it with a regular enum

> b) populate configs with strings rather than int-based enum values
OmegaConf converts the string value to the enum automatically. You can do it with a regular enum

> c) be able to correctly convert previous argparse based configs stored in checkpoints or created in the old entrypoints that would end up having a string value, while still limiting the choices of what people can provide for these options in hydra configs

The part where this might break is "having a string value".
If you are using a regular enum, it's not a string value so comparing it to a string will return False.

d) make migrating models easier, where all checks are done against strings (including models implemented potentially outside of fairseq codebase)

Same as above, I think this will break with regular enums. However, maybe there is a way similar to your current workaround to fix it.
If so, it will still work but mypy will issue a type error for people comparing the enum value to a string, encouraging them to compare to the Enum value.

**Comment by omry** [comment] 2020-11-22 17:34
Here is a code snippet showing using a more normal enum in a way that I think is compatible with your requirements.
I did not try it with submitit:

```
from enum import Enum, EnumMeta
from omegaconf import OmegaConf
from dataclasses import dataclass


class NormalColor(Enum):
    red = 1
    blue = 2


class StrEnumMeta(EnumMeta):
    @classmethod
    def __instancecheck__(cls, other):
        return "enum" in str(type(other))


class SpecialColor(Enum, metaclass=StrEnumMeta):
    red = 1
    blue = 2

    def __eq__(self, other):
        if isinstance(other, str):
            names = [x[0] for x in SpecialColor.__members__.items()]
            return other in names

        return super.__eq__(self, other)


@dataclass
class Config:
    normal: NormalColor = NormalColor.red
    special: SpecialColor = SpecialColor.red


cfg: Config = OmegaConf.structured(Config)
assert cfg.normal == NormalColor.red
assert cfg.normal != "red"

assert cfg.special == SpecialColor.red
assert cfg.special == "red"
```

**Comment by elizgarcia5** [comment] 2020-11-22 21:22
Great work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexeib** [comment] 2020-11-22 21:25
Thanks Omry. 

Unfortunately your suggestion re: `return isinstance(other, Enum) and type(cls).__name__ == type(other).__name__` doesnt work because cls is the EnumMeta class, not the StrEnum class, while "other" is an instance of the StrEnum class.

Re: your suggestion, I agree that there are many ways to make it work, and in principle regular enums are probably better than this StrEnum contraption, but it takes time and effort to do this kind of migration (including in code that relies on fairseq) and at the moment it is probably not the top priority. I will look into how we can promote using regular enums in new components.

This workaround unblocks us for the time being, but my suggestion would be to find a way to make custom classes (and custom enums like here) work without hacks like the one I did, as it would make the framework a bit more robust. Your decision, of course. Feel free to close this issue if you'd like.

**Comment by omry** [comment] 2020-11-22 23:15
@alexeib:
This problem is somewhere in between fairseq, Python, submitit, OmegaConf, Hydra and Cloudpickle.
I have never seen anyone using this kind of enum other than fairseq, and there is a limit to how support I can offer to people that are doing very unusual things. (Not to to mention that I don't even have a hunch as to where to start looking for the root cause of this).

I tried with the enum I proposed above and looks like it's working correctly in every aspect that matters based on your comment about your backward compatibility requirements.

Attached is [standard_enum.zip](https://github.com/facebookresearch/hydra/files/5580563/standard_enum.zip) with a repro, can you take a look and tell me if it's missing anything?

To make it easier to evaluate, here is the code and the output:

**constants.py**:
```python
from enum import Enum


class LOG_FORMAT_CHOICES(Enum):
    json = 1
    none = 2
    simple = 3
    tdqm = 4

    def __eq__(self, other):
        if isinstance(other, str):
            names = [x[0] for x in LOG_FORMAT_CHOICES.__members__.items()]
            return other in names

        return super.__eq__(self, other)
```

**main.py**:
```python
import logging

import hydra
from my_app import Config
from omegaconf import OmegaConf

log = logging.getLogger(__name__)


@hydra.main(config_name="config")
def my_app(cfg: Config) -> None:
    log.info(OmegaConf.to_yaml(cfg))

    if cfg.db.log_format == "tdqm":
        log.info("tdqm detected (as string)")


if __name__ == "__main__":
    my_app()
```

**my_app.py**:
```python
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
from dataclasses import dataclass, field
from typing import Any, List

from omegaconf import MISSING

from hydra.core.config_store import ConfigStore
from constants import LOG_FORMAT_CHOICES


@dataclass
class MySQLConfig:
    # initializing with a string here does not work, but I don't think this is a problem.
    log_format: LOG_FORMAT_CHOICES = LOG_FORMAT_CHOICES.tdqm


defaults = [{"db": "mysql"}]


@dataclass
class Config:
    defaults: List[Any] = field(default_factory=lambda: defaults)
    db: MySQLConfig = MISSING


cs = ConfigStore.instance()
cs.store(group="db", name="mysql", node=MySQLConfig)
cs.store(name="config", node=Config)
```
Run and output:
```
$ python main.py -m db.log_format=json hydra/launcher=submitit_local
[2020-11-22 15:07:47,095][HYDRA] Submitit 'local' sweep output dir : multirun/2020-11-22/15-07-46
[2020-11-22 15:07:47,095][HYDRA]        #0 : db.log_format=json

$ cat multirun/2020-11-22/15-07-46/0/main.log 
[2020-11-22 15:07:47,493][__main__][INFO] - db:
  log_format: json

[2020-11-22 15:07:47,494][__main__][INFO] - tdqm detected (as string)
[2020-11-22 15:07:47,495][submitit][INFO] - Job completed successfully
```

**Comment by alexeib** [comment] 2020-11-22 23:23
Your example looks good to me - but it is conditioned on migrating all of our StrEnums. There is already quite a bit of code using those StrEnums, and going around and changing them all can break things - not to mention the additional code required to keep all the old checkpoints, tasks and models working which use some combination of argparse configuration, serialized Namespaces, etc (including those implemented outside of fairseq main repo), so it is probably not going to happen for some time (unless someone volunteers to do it?). 

As for root cause, I believe submitit's pickling re-imports classes causing class ids to change, which breaks the `isinstance` checks in OmegaConf in the line I pointed out a few comments above.

**Comment by omry** [comment] 2020-11-22 23:34
Yes, it does require moving away from those StrEnums.
I think most of the code that is using them will be assigning and comparing them, and in that sense should not be changed given the example above.
A migration path is to deprecate the existing StrEnum instances (put a warning in the constructor or something) and offer standard variants for people to switch to.

Old checkpoints are indeed a pickle. but I think some changes will always break those.

Submitit is using cloudpickle to do the pickling. generally Python modules are singletons meaning that if they are imported twice the first instance is returned (maybe this is - per scope, local imports are may or may not change the picture).

In your case you are defining the type dynamically which is probably what is breaking things.
I have also something similar without dynamically defined types when using importlib in creative ways in the Hydra plugins system, but I don't think it's related here (A way to prove Hydra not involved is to show that this repros when using OmegaConf and submitit directly).

I doubt submitit can change how it's handling serialization: the cloudpickle project (which is fairly complicated in it's own right) exists just for that purpose and is generally good at it's job.

**Comment by omry** [comment] 2020-12-04 07:18
Closing, let me know if there is anything else you think should happen in Hydra.

**Closed by omry** 2020-12-04 07:18 UTC
Labels: bug
