### ISSUE TITLE
Disable changing working directory

### ISSUE THREAD

**Issue by briankosw** [facebookresearch/hydra#990] opened 2020-09-19 06:10 UTC
# 🚀 Feature Request

Currently, all outputs are redirected to ./outputs/.../.. and I'm aware #910 is addressing this exact feature, but is there a way to patch the current version so that the outputs aren't redirected?

**Comment by omry** [comment] 2020-09-19 06:19
Outputs are not redirected, loggins is configured automatically.
#910 has nothing to do with outputs, it's about working directory.

Can you explain what the problem is instead of what your analysis of the problem is?

**Comment by briankosw** [comment] 2020-09-19 06:29
I realized that the problem is actually that the working directory is changed. What would you say is the best way to change back to the original working directory instead of calling `hydra.utils.to_absolute_path` on every string that's a path?

**Comment by omry** [comment] 2020-09-19 08:41
you can override `hydra.run.dir` to `.`

**Comment by omry** [comment] 2020-09-19 08:42
Closing, let me know if you still have issues.

**Closed by omry** 2020-09-19 08:42 UTC
Labels: enhancement, invalid
